### PR TITLE
Detect and Handle extension updates

### LINKED ISSUE #1675: Is there a way to prevent KC3Kai from automatically closing the game for update?
The update automatically closed my game during sortie. Is there any way to prevent it from updating automatically?

### LINKED ISSUE #1747: tab was closed without confirmation when new version update
sortie in frame mode
exit confirmation is selected
chrome version:55.0.2883.87
Kc3 version from 30.15.0 to 30.15.1

### PR DESCRIPTION
**Pull request by dragonjet**
To finally solve the problem of auto-restarting during webstore updates. This avoids closing extension tabs mid-game.
* Close #1747 
* Close #1675

#### Backend
* Added listener to `chrome.runtime.onUpdateAvailable`
  * This can potentially stop the forced reload on every update
  * Once triggered, we save the new _version string_ in temporary storage
  * New _version string_ in temporary storage cleared every extension startup

#### Menu
* Version-related links in the menu now opens the new update status page below
* Menu will say "_<version_string> available now!_ if the mentioned version string is detected

#### New Update Status Page
* Fetches data from GitHub API about our releases (where `base:webstore`)
* Shows list of releases, including the upcoming pull request
* Clicking on each release will show the description of the release
  * Github pull request description markdown converted to HTML (`markdown.js`)
* Release colors (red = not installed / green = installed)
* Release icons (webstore icon = published / github icon = not yet released)
* Shows yellow banner if there is an available update not yet installed
  * Happens when we see the flag set by the backend, saved in temporary storage
  * Has options to reload extension now or later

chrome_2017-01-22_11-47-35

#### Settings
* Can be disabled, or choose the notification type
chrome_2017-01-22_14-30-44

#### Desktop Notifications
* Can choose desktop notifications which shows like

### Task List
* [x] Handle onUpdateAvailable
* [x] Show update available in menu
* [x] Rework update notification pages
* [x] Add settings to disable update notifications
* [x] Settings to make update notifications as desktop notifications instead of popup tabs

### CODE REVIEW

**Comment by dragonjet** [comment]
@KC3Kai/everyone feature done. ready for review.

**Comment by sinsinpub** [comment]
looks fancy! could we just merge the TL PR first?

**Comment by dragonjet** [comment]
@sinsinpub ah you're right, it's alright to include global.js. will push update soon. including removal of unused terms

**Comment by dragonjet** [comment]
updated. also merged the TL pull request, now pointing to TL repo master.

going to merge by wed, jan 25, before 30.16.0 if no more requested changes by then

**Pull request merged**
