### PR TITLE
Strategy room: ship docking time

### PR DESCRIPTION
**Pull request by Javran**
Modified from ship list, shows non-full HP ships with docking time / facility repair time (Akashi time)

The screenshot should be straightforward:

2015-10-07_152406_3360x1080_scrot

### CODE REVIEW

**Comment by dragonjet** [comment]
oh very nicely done :+1:
I never even though of this XD

**Comment by dragonjet** [comment]
can I edit the page in the branch? I'd like to add HP bars and some other minor ui tweaks

**Comment by Javran** [comment]
@dragonjet feel free to edit :)

**Comment by Javran** [comment]
@dragonjet also there are few things I haven't done, but I won't have time in these few days to take care of them, feel free to take over or comment:

* Refresh the page when switching to it, so remaining docking time will be up-to-date, for now the page refreshes when sorting, but not when switching from other strategy room pages

* `PlayerManager` now adds a field `dockingShips` to localStorage and `docking.js` reads it directly, I guess a better way would be to have some API in `PlayerManager` for reading the data.

 * [shouha / chuuha / taiha status is calculated individually](
https://github.com/KC3Kai/KC3Kai/blob/dev-docking-page/src/pages/strategy/tabs/docking/docking.js#L178-L193) instead of using existing methods in ship object. would be nice to move this part into ship object so other modules can use.

* Mark ships on expedition (like those docking ships but with another color)

* Show some alternative texts when no ship needs repair

* Help topics

**Comment by Crazyteitoku** [comment]
Marking this for documentation.

**Pull request merged**
