### PR TITLE
Enabling ES6

### PR DESCRIPTION
**Pull request by Javran**
enable es6 for KC3Kai

related: #1698

### CODE REVIEW

**Comment by Javran** [comment]
@dragonjet btw I found most of the packages are outdated:

```
 grunt                    0.4.5  →   1.0.1 
 grunt-contrib-clean     ~0.6.0  →  ~1.0.0 
 grunt-contrib-concat    ~0.5.1  →  ~1.0.1 
 grunt-contrib-copy      ~0.8.1  →  ~1.0.0 
 grunt-contrib-cssmin   ~0.13.0  →  ~1.0.2 
 grunt-contrib-htmlmin   ~0.4.0  →  ~2.1.0 
 grunt-contrib-uglify    ~0.9.2  →  ~2.0.0 
 grunt-json-minify       ~0.4.0  →  ~1.1.0 
 grunt-jsonlint          ~1.0.4  →  ~1.1.0 
 grunt-string-replace    ~1.2.0  →  ~1.3.1 
 grunt-webstore-upload  ^0.8.10  →  ^0.9.4 
 jquery                  ^2.2.1  →  ^3.1.1 
 qunitjs                ^1.22.0  →  ^2.1.1 
```

`npm-check-updates` can bump these package versions for us but I'm afraid of breaking changes and hesitated.

**Comment by Javran** [comment]
could be a problem: my first attempt of fixing name shadowing problem in `src/library/modules/Translation.js` is to replace `var` by `let`, this passes jshint, but unit tests are failing:
```
>> global failure
>> Message: SyntaxError: Use of reserved word 'let' in strict mode
>> Actual: null
>> Expected: undefined
>> file:///.../KC3Kai/src/library/modules/Translation.js:138
```

I think PhantomJS (which I believe is what grunt-contrib-qunit uses for the actual js code execution) has not yet supported es6 (but is now quite close, see: https://github.com/ariya/phantomjs/issues/14506), do we need to transpile code just for the purpose of testing?

**Comment by dragonjet** [comment]
we could probably instead remove `'use strict'` from the files, would that help?

**Comment by Javran** [comment]
@dragonjet I think `'use strict'` keeps an eye on many other things that we could have made mistakes so maybe not..

**Comment by Javran** [comment]
labelling this PR as testing, until we can find a way of testing es6 code

**Comment by Javran** [comment]
all done.

@dragonjet @sinsinpub please review changes since last your approval.

changes:

- new directory `patches` for storing patch for external libs
- uglifyJS is patched to use es6-compatible version otherwise build will fail if any es6 syntax is used
- new tmp directory `build/testenv` for testing (until PhantomJS 2.5 is up I think we can do no better than this)
    - copies everything necessary from codebase
    - transpiles non-external js code so that PhantomJS can run
    - transpiling happens only for tests, a direct build (through `grunt build`) still preserves es6 code
- some extra dependencies for all mentioned above to happen

if someone knows how to tell qunit to use `build/testenv` as root directory for testing, please let me know or commit directly on this branch. (but for now this is just a minor issue, and I think current PR is still good enough for merging.

say welcome to es6 (or, more formally, ECMAScript® 2015)! xD

**Comment by dragonjet** [comment]
ah this is the first time I've seen git patches in action.

dont we manually specify in test html file which scripts to import, so we could probably import those from `build/testenv` instead of `../../../src/`

welcome es2015!

**Comment by Javran** [comment]
@dragonjet what about using something like `${testenv}` for specifying the root and in grunt file we could probably replace it with real root path?

**Comment by Javran** [comment]
@dragonjet update: I just tried using absolute path and it doesn't work. not sure what is supposed to be the root directory for PhantomJS, but it doesn't seem to be project root. anyway as long as current relative path works, I'm not worried too much.

**Comment by Javran** [comment]
there are changes since last approvals, but I'm not receiving many comments or approvals on them.
this change could potentially be big so I need more @KC3Kai/developers 's opinion before I feel it's ok to push the merge button.

**Comment by dragonjet** [comment]
I will switch and take a look at this after I finish working on the other branch

**Comment by dragonjet** [comment]
I'm getting this error though
```
>> Uglifying source build/tmp/library/modules/Translation.js failed.
Warning: Uglification failed.
SyntaxError: Unexpected token: name (errMsg).
Line 133 in build/tmp/library/modules/Translation.js
 Use --force to continue.

Aborted due to warnings.
```

runtime:
* node 4.2.1
* npm 2.14.7

**Comment by Javran** [comment]
@dragonjet have you applied the patch? see before_install part of .travis.yml

also note that you need to "npm install" twice, the second time is after applying the patch, for new uglifyJS to be pulled in.

**Comment by dragonjet** [comment]
ah I forgot about the patch, I thought it was just for travis XD
I will rebuild tonight or tomorrow morning, I'm away from my main computer now

**Comment by dragonjet** [comment]
although I had problems applying the patch, building looks good

approved again :+1:

**Comment by dragonjet** [comment]
note: I did not untag the `status:merge-ready` label. I removed the label entirely from repo. Github approvals should work better #1730

**Comment by Javran** [comment]
@sinsinpub any comment on this?

for all @KC3Kai/developers: 
let's allow a ~12 hr window for comments because I really want to hear what other might think about this.
after merging this PR, we can think about ES6 syntax when working with KC3Kai, but readability is always a priority despite we now have access to more fancy stuff.

**Comment by sinsinpub** [comment]
it's okay for me as long as npm & grunt building can be passed perfectly.
not able to test for me as even not have npm installed on my mobile devices...
will more concern at runtime

**Comment by Javran** [comment]
I guess I need to write this down somewhere in case others are experiencing the same problem as @dragonjet did.

in order to build this branch, you need to execute following lines:

```
# npm install -g grunt-cli
# npm install
# patch -d node_modules/grunt-contrib-uglify -p2 < patches/uglify-harmony.patch
# npm install
```

the `patch` command patches `grunt-contrib-uglify` to make it depend on an ES6 compatible version of uglifyJS. and because of this the second `npm install` is needed.
you can also read [`before_install` part of .travis.yml](https://github.com/KC3Kai/KC3Kai/blob/3ae7e489e99b1ed0a86f816ee5b287163a496261/.travis.yml#L4-L7), it lacks the last `npm install` command, which is the default action for travis's install step.

**Comment by Javran** [comment]
@sinsinpub what do you mean by runtime, es6 performance or chrome compatibility?

**Pull request merged**
