### PR TITLE
damaged icons

### PR DESCRIPTION
**Pull request by nonsensed**
Undamaged icons were revisited as well.

### CODE REVIEW

**Comment by sinsinpub** [comment]
didn't we said new sub-folder for damaged icons? 😮 
both are okay tho.
may i add some codes to show them now(in `_d` flavor)?

ps. my internet seems sucked, discord gets blocked for now.

**Comment by nonsensed** [comment]
Yes, sorry about that. I should have written my reason for using `_d`--

I found when working with seasonal icons that it is much easier to change out icons if both normal and _d icons are in the same place.

Please do anything you want to make them work!

**Comment by sinsinpub** [comment]
done, see branch [`dev-chuuha-icons`](https://github.com/KC3Kai/KC3Kai/tree/dev-chuuha-icons)

**Comment by nonsensed** [comment]
Hmm is it possible to make it happen during battles?

in-battle damage

When trying it, it changes after the battle. I think it will be very dramatic for the player to see the icon here if battle prediction is on.

(got to go, I will try it more in the next 24 hours)

**Comment by nonsensed** [comment]
Looking good! So far I haven't found any issues.

**Comment by mikenzb** [comment]
Continued in PR #2285 will close this PR for now.

**Pull request closed without merging**
