### PR TITLE
* export ships to kc3.moe

### PR DESCRIPTION
**Pull request by DynamicSTOP**
moved it here instead of showcase page because
- showcase export button handlers looks too nice and i don't want to break those with ugly ifs
- item export isn't even started
- it's "alpha" and i don't want to mess with current "helping" processes too much, while ui still isn't polished

### CODE REVIEW

**Comment by sinsinpub** [comment]
@DynamicSTOP 
the message event listener will be added to `window` instance of kc3 sroom tab, not the newly opened `window` of kc3.moe. therefore `2 clicks -> 2 new tabs` obviously not solve (even irrelevant to) the duplicated listeners issue.

**Comment by DynamicSTOP** [comment]
In any case double click is blocked now. Should be one listener at max at a time.
Less objects is better, removed ports from both sides. Not sure why i haven't chose that way half a year ago.

**Comment by DynamicSTOP** [comment]
@sinsinpub 
anything else or should i merge?

**Comment by sinsinpub** [comment]
image

**Comment by DynamicSTOP** [comment]
Regarding error. On first load there is no options in local storage so that error is expected . It's triggers by [console.error here](https://github.com/DynamicSTOP/KCExport/blob/master/src/store/modules/options.js#L127) and i think i'll just add length check there later to suppress it until real problems happen. 


Names and length will be fixed later. I've just added [vue-i18n](https://github.com/DynamicSTOP/KCExport/commit/b49409bdff9a86412a009366532a13c359d19ab7) yesterday and i would need to find nice way to load only required langs at a time. There should be similar way to do this through webpack. Then i'll would be able to test names properly. I think German version should have longest words. :D 

Design isn't final at all, i still looking for better ways to display ships and made them look compact and nice. Hopefully Hitomaru will help.

**Comment by DynamicSTOP** [comment]
@sinsinpub 
are you sure about hp?
default

and exported sees it properly
default

like in ship table
default

**Comment by DynamicSTOP** [comment]
and i should probably fix sorting.... again...

**Comment by sinsinpub** [comment]
sure, hp[0] is not master ship's hp[0], its instance's current hp. u need to damage ur ayanami first kappa

**Comment by DynamicSTOP** [comment]
Ahhh... it's current hp. yeah, i should fix that...

**Pull request merged**
