### PR TITLE
Strategy Room: List of ships required by quests

### PR DESCRIPTION
**Pull request by reinforce**
- Add new "Required Ships" tab after Quests -> Flowchart
- Add new "List of ships required by quests" page with ships and quests table

nkxw47r

### CODE REVIEW

**Comment by sinsinpub** [comment]
oh... there is a thing must be changed first: don't put `ship: [questlist]` relationship into `WhoCallsTheFleetShipDb.json`, extracting them into individual json file should do. because `WhoCallsTheFleet` is data set from other open-source project, which will be completely overwritten each time updating it.

**Comment by reinforce** [comment]
So, if I put ship: [quests] data into /data/quests.json it would be ok then?

**Comment by sinsinpub** [comment]
@reinforce yep, perhaps a name like `ship_quests.json` or something is better, not to conflict with the `quests.json` in lang/data

**Comment by DynamicSTOP** [comment]
Cool feature. Looking forward to start using it, since i still have tons of quests to do. Won't increase my free slots but will allow me to plan what ships do i want to levelup next. 

Got couple requests if possible:
1. If quest was already done (e.g. A45 Akashi as flagship) can it have grey background?
2. Buttons\Select\Radio buttons\Anything that will toggle  modes still
- ship still required by some quests
- all related **single time** quests were completed
- no quest needs this ship
3. Sorting by id\name\level

**Comment by reinforce** [comment]
@DynamicSTOP 
Completed quests shoud be marked with green tick, as in flowchart.

**Comment by DynamicSTOP** [comment]
@reinforce 
akashi
I mean i've completed Akashi A45 quest but never did anything related to Kinu and i can't distinguish completed right now. The point was to find ships like Akashi, no?

**Comment by reinforce** [comment]
Hard to track of the quests associated with ships, since QuestManager don't hold statuses of completed quests. Basically this table contain list of player ships and associated quests.

**Comment by reinforce** [comment]
Please review.
Changes:
- Move ships quests DB into data/ship_quests.json
- Add sorting by ID/Name/Type/Level
- Remove quests statuses because QuestManager don't hold statuses of completed quests
- Cosmetic changes

**Comment by sinsinpub** [comment]
good enough, i made some adjustments:

 * `kc3_bship` attribute is not the alternative one of ship's master ID, so just use correct one
 * tooltip contains more info which is the same with flowchart's
 * some naming

feel free to merge to your side, or lemme modify it after this merged

```diff
diff --git a/src/pages/strategy/tabs/shipquests/shipquests.js b/src/pages/strategy/tabs/shipquests/shipquests.js
index 5f8eaaf..0cfccf6 100644
--- a/src/pages/strategy/tabs/shipquests/shipquests.js
+++ b/src/pages/strategy/tabs/shipquests/shipquests.js
@@ -54,7 +54,7 @@
 		prepareShipData: function(ship) {
 			var ThisShip = ship;
 			var MasterShip = ThisShip.master();
-			var Quests = this.getShipQuests(MasterShip.kc3_bship);
+			var Quests = this.getShipQuests(ThisShip.masterId);
 
 			var cached = {
 				id: ThisShip.rosterId,
@@ -156,22 +156,22 @@
 				} else {
 					self.setCurrentSorter( sorterName  );
 				}
-				self.showPage();
+				self.showList();
 			});
 
 			this.shipList = $(".tab_shipquests .ship_list");
-			this.showPage();
+			this.showList();
 		},
 
 		/* SHOW PAGE
 		---------------------------------*/
-		showPage :function(){
+		showList :function(){
 			var self = this;
 
 			this.startTime = Date.now();
 
 			// Clear list
-			this.shipList.html("").hide();
+			this.shipList.empty().hide();
 
 			// Wait until execute
 			setTimeout(function(){
@@ -201,15 +201,15 @@
 					$(".ship_lv", cElm).html( "<span>Lv.</span>" + shipLevelConv);
 
 					Object.keys(cShip.quests).forEach(function(questCtr){
-						var quest_id = cShip.quests[questCtr];
-						var thisQuest = KC3Meta.quest(quest_id);
+						var questId = cShip.quests[questCtr];
+						var thisQuest = KC3Meta.quest(questId);
 
 						var divTag = $("<div />").addClass("ship_field");
 						divTag.addClass("ship_stat");
 						divTag.addClass("questIcon");
-						divTag.addClass("type"+(String(quest_id).substring(0,1)));
-						divTag.attr("title", thisQuest.desc);
+						divTag.addClass("type"+(String(questId).substring(0,1)));
 						divTag.text(thisQuest.code);
+						divTag.attr("title", self.buildQuestTooltip(questId, thisQuest));
 
 						$(".ship_quests", cElm).append(divTag);
 
@@ -218,14 +218,44 @@
 				});
 
 				self.shipList.show();
+				self.shipList.createChildrenTooltips();
 				console.log("Showing this list took", (Date.now() - self.startTime)-100 , "milliseconds");
-			},100);
+			}, 100);
 		},
 
 		shipClickFunc: function(e){
 			KC3StrategyTabs.gotoTab("mstship", $(this).attr("alt"));
 		},
 
+		buildQuestTooltip :function(questId, questMeta){
+			var title = "[{0:id}] {1:code} {2:name}".format(
+				questId, questMeta.code || "N/A",
+				questMeta.name || KC3Meta.term("UntranslatedQuest"));
+			title += $("<p></p>").css("font-size", "11px")
+				.css("margin-left", "1em")
+				.css("text-indent", "-1em")
+				.text(questMeta.desc || KC3Meta.term("UntranslatedQuestTip"))
+				.prop("outerHTML");
+			if(!!questMeta.memo) {
+				title += $("<p></p>")
+					.css("font-size", "11px")
+					.css("color", "#69a").text(questMeta.memo)
+					.prop("outerHTML");
+			}
+			if(!!questMeta.unlock) {
+				for(let ctr in questMeta.unlock) {
+					let cq = KC3Meta.quest(questMeta.unlock[ctr]);
+					if(!!cq) title += "&emsp;" +
+						$("<span></span>").css("font-size", "11px")
+							.css("color", "#a96")
+							.text("-> [{0:id}] {1:code} {2:name}"
+								.format(questMeta.unlock[ctr], cq.code||"N/A", cq.name)
+							).prop("outerHTML") + "<br/>";
+				}
+			}
+			return title;
+		}
+
 	};
 
 })();
```

**Comment by reinforce** [comment]
@sinsinpub `kc3_bship attribute is not the alternative one of ship's master ID, so just use correct one`
I use kc3_bship to get ID of the first ship in series, not the current ship ID.
This is to avoid of duplicating entries in ship_quests.json

**Comment by sinsinpub** [comment]
@reinforce oh, if the 'base remodel form' of ship (ID) needed, `RemodelDb.remodelGroup(currentID)` this function could also be used.
I've not checked the json entries carefully, some quests indeed allow all models in series, but some quests only allow Kai 2 or something, they might be differentiated.
I just notice there are time limited collaboration ships `9182`, `9183` in json, they should not be required by any quest.

**Comment by reinforce** [comment]
Changes:
- Merge @sinsinpub changes
- Use RemodelDb.remodelGroup instead of kc3_bship attribute to get base remodel form
- Update data/ship_quests.json
- Add basic help

**Comment by dragonjet** [comment]
let me know if this is ready :+1:

**Comment by reinforce** [comment]
@dragonjet It's ready

**Comment by dragonjet** [comment]
got it, merging it, good job :+1: 
will add you to credits list, you can specify up to 5 links to be added under your name

**Comment by reinforce** [comment]
@dragonjet Thanks

**Pull request merged**
