### PR TITLE
[Feature #809] Lodger Feature

### PR DESCRIPTION
**Pull request by ReiFan49**
At least, after several weeks though...
This feature is open for test :tada: , (although there might be some patches, such as Taiha blood control, due to mixed problem on earlier commits though)

Requirements:
- Chrome Version: **45** (to perform `fill`, unless you have enabled the **Experimental Flag** since chrome version 36)

Bugs Detected:
- Compatibility Attempt for Chrome **44 and earlier**
- Date shifting system not working properly.
- Remodeling costs is somewhat tricky from the variable name.

Rating Equation Link: http://puu.sh/mpZYl.docx

Bugs and Reports are welcome `'w')/`

Enjoy~
(Marking it as pull request after approved)

PS: this only marks the availability of the feature, even though there's still possible to make it more clear like "Event time", "Specific maps", "Specific Ship".
PPS: akashi interruption costs is 10%?

### CODE REVIEW

**Comment by dragonjet** [comment]
If any of the @KC3Kai/testers are willing and available, can please switch over to this branch `dev-lodger` and play using it,

It's the same as the main branch, it just has a new tab on strategy room that shows where you've spent and gained resources. We'll need multiple days testing, coz this involves daily comparison of resources(?) is that right @ReiFan49?

I've also seen the auto-quest reset code updated so it would be nice if the weekly reset is also tested, that is you have a weekly quest not finished, and at a Monday@5am JST it would automatically reset and removed from your active quests list.

Thanks~

**Comment by LostLogia4** [comment]
Also, requires Chrome version 45 and later.

**Comment by ReiFan49** [comment]
- weeklies problem detected because still progressing the 50 transport quest though, the latest commit hoped to fix this problem.
- sample/data acquired if possible is based from any of those available categories though, (to make sure the data is populated, i guess about 1 or 2 weeks)
- still testing the akashi's repairing part if interrupted after 20 minutes...

**Comment by ReiFan49** [comment]
after i realized, there are some commits that have not been merged yet....

**Comment by LostLogia4** [comment]
The numbers are aligned to the next resource icon, which are confusing for the users.

**Comment by ReiFan49** [comment]
image
somehow i forgot to put that explanation on the commit :sweat_smile:

**Pull request merged**
