### PR TITLE
Update data/edges.json

### PR DESCRIPTION
**Pull request by yukixz**
Using data generated from https://github.com/yukixz/kcmap.
In return for using `edges.json` as source.

### CODE REVIEW

**Comment by sinsinpub** [comment]
kcmap SeemsGood! I'm wondering are those xml/edge IDs extracted from SWFs?
SVGs are drawn manually or not?

**Comment by yukixz** [comment]
There are only two manual action:
1. Download and convert map swf to xml.
2. Mark spot name(letter).
Then kcmap/kcmap.es will extract information from xml and draw svg.

**Comment by yukixz** [comment]
I wrote a post about how kcmap works.
http://blog.dazzyd.org/blog/how-to-draw-a-kancolle-map/

**Comment by dragonjet** [comment]
looks good @yukixz thanks :+1:

**Pull request merged**
