### PR TITLE
Fleet Viewer

### PR DESCRIPTION
**Pull request by Javran**
modified on top of Fleet > Current

* support viewing current fleets
* can load all fleets from sortie history
* can save fleets with a user specified name (with renaming / deletion support)
* exporting to deckbuilder

2016-05-10_070642_3840x1080_scrot

### CODE REVIEW

**Comment by Javran** [comment]
Solves #1062, related: #1357 

@JD-Kurotoshigami see if this is something similar to what you want

**Comment by dragonjet** [comment]
can we rename the tab into Fleet Manager? seeing there are save/load button as well

**Comment by JD-Kurotoshigami** [comment]
yep this is pretty much what i had in mind
Manage Fleet
:'>

**Comment by dragonjet** [comment]
oh @JD-Kurotoshigami I thought you wanted something like even arranging the positions in strategy room and changing equipment, that's why I suggested deckbuilder XD

**Comment by JD-Kurotoshigami** [comment]
which is why i said "pretty much"
:'>
that's the only thing i don't see here

**Comment by Javran** [comment]
updated, now called Fleet Manager.

**Comment by sinsinpub** [comment]
there are also things could be done to enhance current fleet page:
 * new LoS sum
 * plane proficiency
 * gear improvement
 * ex-slot item
 * link to ship/gear list

**Comment by Javran** [comment]
@sinsinpub I'm thinking about making this page to users asap and have no further plan of working on it. feel free to take over though.

**Comment by dragonjet** [comment]
tested it my side too, great work :+1:

**Pull request merged**
