### PR TITLE
Quest tracking stuff for C8: Elite Fleet Practice

### PR DESCRIPTION
**Pull request by bcc32**
DON'T PULL THIS YET.  I haven't worked out how to fix it so that all 7 victories are in the same day but the quest only comes around once per month.

### CODE REVIEW

**Comment by dragonjet** [comment]
i haven't done it yet so I could probably test if needed

**Comment by bcc32** [comment]
Should be done.  Please try and let me know.

**Comment by McDohl** [comment]
@bcc32 mind to check this https://travis-ci.org/KC3Kai/KC3Kai/builds/79498575 ? travis kun is angry xD

**Comment by bcc32** [comment]
I missed a comma. (facepalm)

**Comment by McDohl** [comment]
@bcc32 I reverted it back to before I merged this. I adviced to make a new pull xD

**Pull request merged**
