### PR TITLE
Replace some tool-tips with rich text

### LINKED ISSUE #1718: Suggest to import tooltip UI library
Introduce and apply a tooltip lib such as jQuery UI (already there) Tooltip as we have quite  lots of usage...

Current native tooltip shortcomes:
 * No html, no styles. This prevent us to show some icon images or complex table on tooltips.
 * Not react on touch events.
 * Not fixable, all relying on mouse pointer hovering only.

For now we may just replace partial tooltips which need those features, leave some native still.

### PR DESCRIPTION
**Pull request by sinsinpub**
Close #1718

### TODOs

 * Import jquery-ui library widget `tooltip` and its css
 * Benefits:
   * Contents with rich text of HTML and CSS
   * Easy to compatible with old `title` attribute
   * Customizable position
   * Not intended, but also react to touch tap event
 * Lack of jquery-ui tooltip: Not fixable, tool-tip will closed on mouse-enter; no real touch events supported; sometimes auto position weird.
 * Replaced following native tool-tips with rich text one:
   * [x] Quest flowchart detail of Strategy Room
   * [x] Quest detail tool-tip of natsuiro theme panel
   * [x] Ship face icon tool-tip of natsuiro theme panel
     * Also add this tool-tip to Strategy Room Fleet Manager
   * [x] Enemy face icon tool-tip of panel's Battle activity

if any other tool-tip would like to be replaced or improved, leave a comment or suggestion.

### Screenshots:

on quest flowchart:
image

on ship of panel:
image

on ship of Fleet Manager (dark theme):
image

on enemy face icon:
image

### CODE REVIEW

**Comment by sinsinpub** [comment]
Almost all the tool-tips of natsuiro panel are replaced, except following:

 * Tool-tip popup might block clicking
 * No variable values in tool-tip, just a static description text

Feels better when play on touch screen device from now 🎃 

Feel free to merge this for pending release if no more tool-tip to be improved.

@KC3Kai/translators old terms: `ShipAAImgEnemySlot` and `ShipAAShotdownPred` will be not used if this merged, could be safe to removed them. character `/` in new term `ShipAAShotdownTitles` is important, used to split into 5 captions.

**Comment by Javran** [comment]
just an improvement suggestion: maybe we can apply a different color on ASW if its stat is >= 100, to show that the ship is question is capable of OASW.

but the actual rule is slightly more involved than this, as another requirement of OASW is that sonar should be equipped. so I just added [`Ship.prototype.canDoOASW`](https://github.com/KC3Kai/KC3Kai/commit/454bee894cee3eab9281130238d61b285376afa4), you can as well use that.

**Comment by sinsinpub** [comment]
@Javran okay, and a color for Fast+/Fastest

**Comment by Javran** [comment]
@sinsinpub you are right about isuzu k2, that was my fault, fixing it.

**Comment by dragonjet** [comment]
wow I really like the UI, cheers! :clinking_glasses:

**Comment by sinsinpub** [comment]
@dragonjet oh, i just recall a grunt build testing might be required for this, to see if packaged one includes new assets or not

**Comment by dragonjet** [comment]
@sinsinpub yep, seems `jquery-ui.min.js` and `jquery-ui.min.css` are in the build directory in their respective folders. is there any other file to watch out for?

**Comment by sinsinpub** [comment]
no other. should be ok as long as ref link in html files is correct.

**Pull request merged**
