### PR TITLE
new page : data load room

### PR DESCRIPTION
**Pull request by Yukinyaa**
scshot

solution for #1221

### CODE REVIEW

**Comment by Yukinyaa** [comment]
ok this was not a very clever idea.

**Comment by dragonjet** [comment]
wat u mean? XD

**Comment by Yukinyaa** [comment]
Oh I was making mistake nvm

**Comment by Yukinyaa** [comment]
Some design on html and we're good to go 👍

**Comment by dragonjet** [comment]
alright ill take on the UI for this too ill push onto this PR when ready

**Comment by sinsinpub** [comment]
wait... if it's just a link to data Backup tab...I have changed the behavior at PR #1191 
Tab menu list will not be stopped from loading even localStorage master missing, user can still go to Backup tab to import data :joy:

**Comment by dragonjet** [comment]
@sinsinpub, it seems @Yukinyaa separated the whole backup page into its own page XD

@Yukinyaa is it possible to cherry-pick only your changes in the `DataBackup.js` module? Seems #1191  handles it better

**Comment by Yukinyaa** [comment]
@dragonjet yes,just keep the DataBackup.js and remove all other changes. it's fine that way

**Comment by dragonjet** [comment]
@Yukinyaa ill make a `dev-databackup-2` branch, and delete this one since it already have changes we won't push to master. If you have more changes afterwards, create a new branch `dev-databackup-3`

**Pull request closed without merging**
