### PR TITLE
[dev-sroom-helps] Strategy room enhancement

### LINKED ISSUE #1179: Update Strategy Room help messages
I'd like to change the help messages in several tabs of strategy room.

Motivation:
 * Help texts always keep on the top of page, take spaces of limited screen (my laptop screen resolution is so low :sweat_smile: 
 * A little annoyance for those had read them again and again (and for those never understand the exact meanings as they are not translated for now

Solution:
 * Move the messages not so important into `Help Topics` on the right top. A friendly pop up to remind new user to read the Help Topics is nice.
 * Mandatory notice must be read should be able to be dismissed if user has read and confirmed it. And the notice can be found at `Help Topics` again.
 * More useful offline help messages (such as graph legend, FAQ) could be added to `Help Topics` and detail guides could be linked to github wiki pages.

implementation: the dismiss of CG Viewer notice can be checked at a new wip branch `dev-sroom-helps`

Any suggestion and discussion welcomed.

### PR DESCRIPTION
**Pull request by sinsinpub**
Close #1179 

Summary of this PR:

* Major features
  * **Single-page style implementations**: This includes 2 major things:
    * Simulate hyper link jump among tab pages and carry arguments via URL hash. Browser history (Back/Forward buttons) will work properly for tab switching
    * Support reloading tab pages (data) on demand without using reload button of browser
* Features rely on major
  * Make ship icon and gear icon clickable, to jump to corresponding library page
  * Improve those pages with sub tabs, support direct linking without click from default
  * Improve quotes dev page
* Features may not rely on major changes
  * Update Help Topics texts
  * Move some hint messages into Help Topics and make them dismiss-able (disappear from top of page)
  * Show more stats for ship library page, enhancements for abyssal ships
  * Hide unused ship types for ship list page
  * Enhance translation dev page
  * Misc logging and exception handling improvements
* Planned features (Not implemented, gonna seperated to another branch)
  * Proprietary i18n support for Strategy Room pages

### CODE REVIEW

**Comment by LostLogia4** [comment]
Someone won't be happy if the Analytics is taken out of the code. :(

**Comment by sinsinpub** [comment]
gap? it has never been taken out... contrarily it will be run more even user push back button :sweat_smile:

**Comment by sinsinpub** [comment]
@dragonjet A question:
Finally I have moved Google Analytics event code to the click event of tab to avoid duplicated event for each time a 'hyper-link' clicked or the back button of browser pushed. Is this okay? Or would u like more events including the url hash values tracked by GA?

**Comment by dragonjet** [comment]
tbh I'm not really looking at the stats atm. I just thought it would be useful at some point that's why I added those tracks, but not right now. so which ever works best, to avoid duplicates and stuff, I agree :+1:

**Comment by ReiFan49** [comment]
about reverting the API revert, the popup doesn't recovered yet XD
(i'll check more)

**Comment by sinsinpub** [comment]
don't worry
I'll sync with master and remove the revering commit to avoid conflicting with `dev-api-2`

**Comment by sinsinpub** [comment]
Full stats for shipgirl in library, powered by WhoCallsTheFleetDb.
image

(but still no data for new ships such as satsuki K2, ooshio K2)

**Comment by Javran** [comment]
@sinsinpub just updated WhoCallsTheFleet db, satsuki k2 & ooshio k2 should now have evasion & asw attributes.

**Comment by mikenzb** [comment]
I was just thinking wouldn't it be nice if there was an refresh button on some pages in the strategy room.

Say you're looking for a high angle gun in the equipment list but you take it off and you want to check if anyone else still has the gun you have to reload the whole page which drops it back the normal small DD guns and I was thinking it might be nice to have an built in reload button so you don't have to reload the whole page

**Comment by sinsinpub** [comment]
@mikenzb yes, refresh button planed (for all tabs). But there is already 'buggy' thing for equip list when equipment changes... more efforts on this tab required :smiley:

**Comment by sinsinpub** [comment]
About new tab reload mechanism, I left the remarks at `objects/StrategyTab.js`:
```
	/**
	 * Terms of callback function definitions:
	 *   "init": Invoked for the first time tab initializing, only once (for once browser refresh).
	 *   "reload": Invoked when data loading required, optional once, may many times on demand.
	 *   "execute": Invoked for rendering HTML content for each time tab is shown.
	 */
```

**Comment by dragonjet** [comment]
i fear that i18n  for straegy room will be a big undertaking. I recommend setting it aside to another branch, so we can clear/merge this separately from i18n

**Comment by sinsinpub** [comment]
@dragonjet yes, I think so too. let me do some cleanup and finalization. when done mark it merge ready.

**Comment by sinsinpub** [comment]
NOTE: Anyone would not be able to open IndexedDB normally if have tested this branch once.
Because the DB version has been upgraded, and Ive removed the related codes from this branch.
Merge the branch of PR #1350 will solve it.

**Comment by sinsinpub** [comment]
Enlarged abyssal ship view:
image

**Comment by dragonjet** [comment]
if that's the case we could probably make another flash file for abyssal ships, what's the dimensions?

**Comment by sinsinpub** [comment]
@dragonjet problem is we don't know exactly. expected size is always different from ships to ships, have tried to retrieve from official swf before, but failed :sweat_smile: 
Current one I just resize the embed container to 100% width and 400px height. it's nice if the swf could be auto fit with any size (main the gradient background?)

**Comment by dragonjet** [comment]
yep I just mean the dimensions of the flash container of the embed in the strategy room page XD

**Comment by dragonjet** [comment]
should we bump to v31 for this? usually major versions are just bumped for non-backwards compatible changes, but if everything will still work using old data stored on cache, we can just bump to 30.2.0

**Comment by sinsinpub** [comment]
@dragonjet just affecting SR and work for current data, nothing for non-backwards compatible. `30.2` may be okay.
the encounters IndexedDB upgrading is not backward compatible.

**Comment by dragonjet** [comment]
does this mean their encounters list will be cleared upon upgrade? if not, let's go for 30.2

**Comment by sinsinpub** [comment]
@dragonjet no, will not be cleared. And encounters related is now in PR #1350 , not talking about this branch. :laughing:

**Comment by dragonjet** [comment]
alright perfect, will merge this now for 30.2

**Pull request merged**
