### PR TITLE
Upgrade jQuery version to latest 2.x

### PR DESCRIPTION
**Pull request by sinsinpub**
Minor upgrade, from 2.1.3 to 2.2.4, no migrating guide found. Suppose to be compatible. For #1876 

Just to test: grunt built package works or not, because version removed from file name. (not sure is version in file name really necessary? @dragonjet)

### CODE REVIEW

**Comment by reinforce** [comment]
@sinsinpub I think it's better to keep version in file name for fast version checking.

**Comment by sinsinpub** [comment]
@reinforce i don't feel necessary... for human, check it at first line comment. for computer, access `jQuery.fn.jquery` will be fast enough.

**Comment by Javran** [comment]
actually jquery is the only thing that has a version in its name, now that the version number is in head comments so we didn't loss any info.

**Comment by dragonjet** [comment]
yep, jquery version in filename is good :+1:

**Pull request merged**
