### PR TITLE
Release 27.6

### LINKED ISSUE #1210: localstorage.maps = 'null'
I recently cleared local storage data,
and I have no idea why but, localstorage.maps remains 'null'.
this causes map tab to be distorted with error ```Uncaught TypeError: Cannot read property 'm11' of null```, 
and sortie log not being displayed.

### LINKED ISSUE #1212: Player scale functionality not work
player scale function in setting not working on chrome 49.0.2623.87 m

### PR DESCRIPTION
**Pull request by dragonjet**
* Updated TL pointer
* Disable KC3 Online
* Rank pt: /1428
* Rank pt: Last day of month 22 JST at night via wikiwiki
* Add current/max exp to profile tab
* World 6-4 Gauge
* Further fix for TL ability in ship name suffixes
* Fix #1210 Recover from localstorage.maps = null
* Fix #1212 Game Player Scale

### CODE REVIEW

**Comment by dragonjet** [comment]
If possible, include #1212 to this release

**Comment by sinsinpub** [comment]
have a look at the reverting commit of api files at my branch: 46a77a6

**Comment by longkagamine** [comment]
may i ask?
why on the chrome store it's still ver 27.5 :(

**Comment by dragonjet** [comment]
@sinsinpub will take a look and sort it out this long weekend

@longkagamine we haven't pushed the button to put it into the webstore

**Comment by dragonjet** [comment]
@sinsinpub can we merge that? or should we do it separately in master branch if we'll need to release it on this 27.6?

**Comment by sinsinpub** [comment]
@dragonjet it's okay for me to merge.
and I realized that it's not enough for me to improve help topic texts 'cause of my poor English :sweat_smile: it needs help of u all

**Comment by dragonjet** [comment]
we can probably do it as translatable as well, in the TL repo. so just add the messages as constants we can specify in the en files

**Comment by dragonjet** [comment]
wait why did this fail build, and is referencing an [inexistent PR](https://travis-ci.org/KC3Kai/KC3Kai/builds/117740077)

**Pull request merged**
