### PR TITLE
Release 31.5.0

### LINKED ISSUE #1378: Wrong Akashi Timer in the main panel
In the current setting, Akashi timer in the main panel would reset every time you go back and forth to the lobby. However, this is not correct since the timer won't reset if you don't change the fleet. This bug makes the Akashi timer totally useless since it will always give you wrong count on the time.

### LINKED ISSUE #1942: De-duplicate Image Output
Showcase Export, Screenshots and Replay Image output should share the code for outputting an image.

### LINKED ISSUE #1967: [Suggestion] Blinking the resourse when its reach max regen cap
As suggested 
can u guy made the resourses in "BASIC" tab  blinking when it reached it max soft cap depend on HQ level ? 
even better if it show how many res to soft cap / how long to natural regen reach soft cap when hover it

### PR DESCRIPTION
**Pull request by Vultren**
### ⚓️ Features & Enhancements

* [#1896](https://github.com/KC3Kai/KC3Kai/pull/1896) Akashi repair timer reworks (Fix #1378, #1678)
  * Fix timer reset behavior
  * Improve accuracy of repair time prediction
* [#1959](https://github.com/KC3Kai/KC3Kai/pull/1959), [#1965](https://github.com/KC3Kai/KC3Kai/pull/1965) Sync Quests tracking data on different machines via Chrome Storage
  * To use this feature, you should enable account synchronization of your Google Chrome browser (especially for Chromium, should compiled with sync enabled). Not tested on other Chromium-based browsers.
* [#1948](https://github.com/KC3Kai/KC3Kai/pull/1948) Image exporting reworks (Fix #1942, #1936)
  * Fix uploading screenshots to imgur bug
  * Showcase exporting & Replay downloading also follow output settings of Screenshots
  * Strategy Room Screenshots can also manage imgur images of showcases & replays
* [#1975](https://github.com/KC3Kai/KC3Kai/pull/1975) Push notifications to mobile via PushBullet
* [#1970](https://github.com/KC3Kai/KC3Kai/pull/1970) Color regen & hard cap of panel resources & consumables (Fix #1967)
  * Show left time to regen cap on tooltip of resources
  * New setting to configure hard cap warning threshold
* [#1966](https://github.com/KC3Kai/KC3Kai/pull/1966) Improve expedition panel GS rate prediction
  * Implement KCKai (PSVita) formula for GS rate
  * Add more possible colours for GS rate text
  * Refine tooltip for GS rate

### ⚓️  Fixes & Adjustments

* [#1972](https://github.com/KC3Kai/KC3Kai/pull/1972) **Strategy Room Showcase**: Fix image exporting alignment of single line equip name, wrap long word in light mode
* **Strategy Room Docking & Ship List**: Fix icon position
* **Strategy Room Ship Library**: Update AACI patterns, show blueprint consumption for next remodel
* **Strategy Room Expeditions History**: Show full date time tool-tip
* **DMM site play mode**: Fix scroll down by Tab key issue, hide 1 pixel bright dot
* Update Remodel DB to support consumption of devmats, torches, blueprint & catapult
  * **Recommend**: to update your cached remodel info, click the `Clear Ship Remodel Information` link once at Strategy Room Profile page

### ⚓️  Translations & Data

* Icons for Suzuya Kai Ni, Suzuya-Kou Kai Ni
* WhoCallsTheFleet DB, Akashi improvement info
* `en` equiptype
* `en` items
* `en` quests
* `en` quotes
* `en` ship_affix
* `en` ships
* `en` terms
* `jp` equiptype
* `jp` quests
* `jp` quotes
* `jp` terms
* `kr` items
* `kr` quests
* `kr` ship_affix
* `kr` ships
* `ru` quests
* `ru` terms
* `ru` ships
* `scn` servers
* `tcn` quotes
* `th` battle
* `th` quests
* `th` quotes
* `th` ship_affix
* `th` ships
* `th` terms

### CODE REVIEW

**Comment by FOG-Yamato** [comment]
The notifications are for both android and iOS, #1967 bullet points should be in hierarchy like ones for GS

**Comment by Vultren** [comment]
whoops Let me change that

**Comment by Adrymne** [comment]
### Suggested Changes

> **Docking** icon top poisition fix
> **Quests** data synced on different machines via Chrome Storage
> **Ship List** icon top poisition fix
> **Showcase** fixed alignment for single line equip name
> **Showcase** fixed split for long words in light mode

Should probably match the present imperative tense of the rest of the notes. Something like:

**Docking:** Fix top position of icons
**Quests:** Add data sync between different machines via Chrome Storage
**Ship List:** Fix top position of icons
**Showcase Export:** Fix text alignment for single line equip names
**Showcase Export:** Fix text alignment when splitting long words in light mode

>more faithfully models the logic used by the game to determine how long an Akashi repair has been running

Maybe split it up to be a bit more precise:

  - Fix timer reset behaviour
  - Improve accuracy of repair time prediction

(Also, "Akashi Repair timer rewrite" isn't present imperative tense)

> Update AACI pattern **predication**

Should be "prediction".

> mobile notification implementation

Again, present imperative tense (also should be capitalized).

> Image export optimization

A bit vague. The interesting user-facing changes are probably:

- Fix Screenshot bugs
- Showcase export and replay image download now respect the Screenshot options in Settings.

> Finishing additions for Suzuya Kai Ni
> Shifting of IDs of fog fleet from 1900s to 2000s

Tense again.

**Comment by DynamicSTOP** [comment]
>Showcase Export: Fix text alignment when splitting long words in light mode
There was no split before and it's not about text alignment. Eh, anyway nobody would read it. 🤣

**Pull request merged**
