### PR TITLE
Add overlay to show node markers for sortieing to old maps

### PR DESCRIPTION
**Pull request by sinsinpub**
TASKs:

- [x] Add new overlay to API and DMM game mode to show markers
- [x] Add new TMsg service to pass event data on sortieing start and to next node
- [x] Add new JSON data for markers such as node letters, get item icon, boss face, etc
- [x] Add new setting option for this feature

TODOs:

 * Icon markers for BOSS (whole-length pictures) not ready, using face instead.
 * Nodes data is WIP.  Could complete it later after merging this. Current progress:
    - [x] World 1 (1-6 has official letters)
    - [x] World 2
    - [x] World 3
    - [x] World 4 (4-5 has official letters)
    - [x] World 5
    - [x] World 6 (letters for 6-1, 6-2 only)

### CODE REVIEW

**Comment by sinsinpub** [comment]
it's nice if anyone could test this via DMM frame mode 😃

**Comment by dragonjet** [comment]
wow this is an exciting feature :+1:

**Comment by dragonjet** [comment]
we can merge this as long as it catches and no error if there's no data for that specific map?

**Comment by sinsinpub** [comment]
yes. marking on a map without data will be just ignored

**Pull request merged**
