### PR TITLE
Improved hardcap warning & Added mobile notifications

### PR DESCRIPTION
**Pull request by FOG-Yamato**
Added max Coin constant to PlayerManager

### CODE REVIEW

**Comment by FOG-Yamato** [comment]
Well without the warning lets ppl be aware of getting close to it so they can change the grind maps and such, but I can't say that it's useful since I never reached the hardcaps myself.

**Comment by FOG-Yamato** [comment]
Added PushBullet notifications, the translation files need a update aswell.

**Comment by Tedster59** [comment]
how does this notification thing work?

**Comment by FOG-Yamato** [comment]
Yes it absolutely does.
image

image

**Comment by FOG-Yamato** [comment]
You have to make an account on PushBullet, create a API key, add it to settings, download the phone app and you're good to go.

**Comment by Tedster59** [comment]
OK, that makes sense.

**Comment by Nya-chan** [comment]
@sinsinpub Pretty sure some of the "you are close" warning are useful - I've personally seen only the coin case (somebody didn't know about hardcap while being close to it and opened lots of boxes, all extra coins lost), but there's no telling for whome else it might be useful.

**Comment by sinsinpub** [comment]
the push notification feature, i break it into another branch: [dev-mobile-push]( https://github.com/KC3Kai/KC3Kai/tree/dev-mobile-push). @FOG-Yamato u could open a new PR. and suggest to write a wiki page to introduce the usage, then add the help link to the settings.

closing warning is okay for me, my point is how those thresholds are defined. eg: warn from max ships - `5`, max slotitems - `20`, they are defined in game. better to have the opinion of person whose resources always near the hardcap, isn't it? so finally, i made it configurable, default value is 95% of hardcap.

**Comment by FOG-Yamato** [comment]
Alright sounds good!

**Pull request merged**
