### PR TITLE
Improved docking tab

### PR DESCRIPTION
**Pull request by Javran**
- code cleanup
- keep ship info sync-ed (don't have to refresh page)
- pink indicator when a ship is being repaired by akashi:
2016-02-11_193057_3840x1080_scrot

### CODE REVIEW

**Comment by ReiFan49** [comment]
sounds interesting, 

but, ships have `akashiMark` that marks being repaired by akashi and fleets have `checkAkashiExpire` if the tick has been run at least 20 minutes since set.

**Comment by Javran** [comment]
@ReiFan49 I attempted to use `akashiMark` but it's out of sync when I use "dismiss all but flagship" in game. the debugging log show ship name & akashiMark, zuikaku & ooyodo is not docking while `akashiMark` is set to true. 

2016-02-17_144449_3840x1080_scrot

I don't want to be accurate on akashi timer unless it's easy to implement, because it's a strategy room page, user might want to browse it offline so I'm trying to avoid using info available only when game is started.

**Comment by ReiFan49** [comment]
dismiss huh, maybe i haven't noticed it orz (even though a little bit out of topic i guess)
image
and
```
	// ShipManager.js
	cShip.akashiMark &= !!cShip.onFleet();
```
(also, zuihou...) 

thanks for noticing this 'w')

**Comment by dragonjet** [comment]
is it clear to merge this or are there outstanding errors to be fixed?

**Comment by Javran** [comment]
@dragonjet it's ready for merge. Will adapt to use `akashiMark` in future but for now I'm good with it.

**Comment by dragonjet** [comment]
thanks :+1:

**Pull request merged**
