### PR TITLE
Small fix / updates

### PR DESCRIPTION
**Pull request by freezebear**

### CODE REVIEW

**Comment by ethrundr** [comment]
ayyy Travis is angry again XD

**Comment by freezebear** [comment]
huehuehuehue.... why.... =w=;
do you really hate me.. T^T

**Comment by ReiFan49** [comment]
lol it's not you.. i know who did it..... *escapes*

**Comment by ethrundr** [comment]
@ReiFan49 fix it already won't ya XD

**Comment by ReiFan49** [comment]
@ethrundr  wait, i just restarted my computer lol

**Comment by dragonjet** [comment]
is this merged? this is not what travis-kun is angry about :laughing:

**Comment by ethrundr** [comment]
Whoa Travis-sama is still angry....

**Comment by dragonjet** [comment]
merged it, the build error was from a separate file

**Comment by McDohl** [comment]
its because @freezebear and @bcc32 forked when travis is angry due to @ReiFan49 commits so yeah their forked is marked as error xD

**Comment by bcc32** [comment]
Derp forgot to rebase my last patch.  Oh well.

**Pull request merged**
