### PR TITLE
New Gameplay Mode

### LINKED ISSUE #425: Screenshot Feature Re-enabling In the Direct DMM Website Gameplay
As we all know, since the gameplay moved from DMM Frame to the Direct DMM Website, the screenshot button is rendered not functional anymore and will just disappear once you attempt to take a screenshot using it. 

This make we need to resort to our classic way of screenshot-ing the frame: Windows PrintScreen, Snipping Tool, Grab or any other similar tools. This way of taking screenshot will require a little bit more work to do, and tend to miss important scenes where timing is important, like destroying the boss bars, branching before the formation selector appears, wedding scene, etc.

Thus, this feature is somehow needed to be re-enabled in the Direct DMM Website gameplay, for instant screenshot for important scenes, as well as for easy screenshot-ing. This not need to be in next version, instead you guys can take time for more important update first before implementing this, but make sure you still implement this feature someday in future.

Cheers, guys~

### LINKED ISSUE #890: OSAPI?
I heard that except the regular API link, there are also a type of api link called as OSAPI link which have shorter lifespan and thus more secure. How about adding an option to fretch and play with osapi?

### LINKED ISSUE #1033: DMM网页模式 截图不能?
@Javran 点击development面板上的那个截图按钮, 但是却不能截图,不知道你们有没有发现

### LINKED ISSUE #1274: [Bug report] Game freezing on right click in frame
I've run across this issue a couple of times today when the game will freeze on the last screen you were on when I accidentally right-clicked on the game in the frame. This issue doesn't clear and I had to refresh the game to get to work again. This same issue also causes the Strategy Room to be inaccessible as a result.

### PR DESCRIPTION
**Pull request by dragonjet**
A smaller pull request than #1645

* This branch now doesn't remove API Link and DMM Frame gameplay options
* Is only and additive to existing background script, doesn't replace existing functions
* Doesn't replace existing injections
* Only includes special DMM mode only, does not have online translations which the other branch already incorporated
* Doesn't remove many settings that the other branch deprecated

## Updates
| Area | Description | Screenshot |
|---|---|---|
| **Menu Updates**  | Smaller API link and DMM frame options  | 
| **New Play landing page** | Opens when selected the "_Play on DMM Website_" option  | chrome_2017-01-23_07-59-12 |
| **New idle Timer** | Shows up after configurable idle time. Slowly fades to darker screen for 100 seconds, Click to dismiss until next idle time  | chrome_2017-02-07_12-24-20 |

## Related Issues
* #1641 Chrome Version 55: Black screen
* #1643 [Issues] Panel don't start
* Close #425 Screenshot Feature Re-enabling In the Direct DMM Website Gameplay
* Close #1033 DMM网页模式 截图不能?
* Close #1274 Game freezing on right click in frame
* Close #890 OSAPI

### Customization
- [x] Customizable Background Images
- [x] Cuztomizable Game Frame Margins

### Overlays
- [x] Subtitles
- [x] Quest Translation Overlay
- [x] Non-TL'ed Quest GT link
- ~~Annoying Taiha Alert~~
- [x] Map Markers Overlay
- [x] Idle timer

### HotKeys
- [x] <kbd>F7</kbd> Toggle keyboard focus
- [x] <kbd>F9</kbd> Trigger screenshot
- [x] <kbd>F10</kbd> Clear all current overlays

### Other
- [x] Exit confirmation
- [x] Screenshot
- [x] Fit Screen

### Integrations
- [x] New menu option
- [x] New landing page for "Play" menu option

### CODE REVIEW

**Comment by dragonjet** [comment]
@KC3Kai/everyone i think this one is ready for test. would be nice if you guys can review, checkout the branch and test it locally, to get a feel of the gameplay mode. see if I missed something or whatnot.

**Comment by sinsinpub** [comment]
Have tried on my side lightly (not try every features, just reload & restart ext many times 😂 ), looks fine.
Left issues might be the unTLed new terms.

**Comment by dragonjet** [comment]
ah since travis wasnt running I didn't know there were build errors

**Comment by dragonjet** [comment]
@KC3Kai/everyone all current bugs / forgotten things before have now been fixed or added. ready for be reviewed again

**Comment by sinsinpub** [comment]
a side-effect about this mode:
`background-size` of customized background image will not be the same size with old modes, because for this mode, browser set body height: 0px, style `cover` will not be able to resize image to fit with the height.

**Comment by dragonjet** [comment]
@sinsinpub ah I've encountered that before, but it's alright it's only aesthetic setting

loading of TL files not yet supported here. it will be done in another branch after this one is merged

**Comment by Javran** [comment]
just tried this branch and it all looks fine. but there is one problem: I feel this approach is a bit on the intrusive side: when KC3Kai is installed, the link to the game automatically cut off other stuff, making it inconvenient to add money to your DMM account / check game announcement or ranking result of past month, etc. I'd suggest leaving an option for user to opt out when necessary.
(I just resolved the conflict, the only conflicting thing seems to be TL repo this should be fine.)

**Comment by sinsinpub** [comment]
also feel that, althoughi never wanna see dmm contents...
so a method needed for injection scripts to know it's started from kc3, not direct opened dmm. and for error report, we also need to know user playing via which mode.

**Comment by dragonjet** [comment]
you can toggle the "Apply customizations" then refresh the tab (no need to refresh extension), the UI will then not be applied. To re-apply it, play menu again and toggle the same customizations switch

**Comment by Javran** [comment]
@dragonjet just tried and that does work as expected! I think we do need to tell user about this as it affects web pages outside KC3Kai. btw I notice menu entry for API link and DMM Frame no longer have a description, is that intended?

**Comment by dragonjet** [comment]
@Javran ah I just realized what you were talking about, I didn't visit other DMM pages while on this, so I didn't notice it's affecting other pages other than game page. yes I'll do something about that aspect of user experience, will think about good approaches.

yep the descriptions were removed, and once users are eventually better acquainted with the new usage, we'll remove it from menu especially once chrome flags back the DMM frame black screen and the API link problem.

**Comment by Javran** [comment]
@dragonjet would you consider bringing this timer to this new mode?

2017-01-25_143540_3840x1080_scrot

honestly I don't know why but I'm used to having it around xD.

**Comment by dragonjet** [comment]
@Javran that was one of the features I was hopign to be forgotten and not re-implemented in the new one tbh XD including annoying taiha alert. as far as I remember this idle timer was added only during the time there was an API catbomb scare, and that API links expire after sometime idle. iirc this was also just for testing and not for player-use.

**Comment by mikenzb** [comment]
If we're planning to removing the idle timer I feel like we should at least fix the akashi timer #1378 built into KC3, as that's what I use the idle timer for.

**Comment by dragonjet** [comment]
I can't find out a good way to deal with injections done outside of _play game_. I feel it's kind of natural and understood that once you enable customization it will always apply. This is because the setting, `dmm_customize` is disabled by default, and they need to explicitly toggle it on.

also, hmm I just got an idea for an idle timer.. let me try experimenting a bit..

**Comment by dragonjet** [comment]
I think im done with this at its current state. If there's any other follow up we need we can do another pull request. Will wait for a few more days for comments / approvals before merging.

**Pull request merged**
