### PR TITLE
Update terms.json

### PR DESCRIPTION
**Pull request by freezebear**

### CODE REVIEW

**Comment by Crazyteitoku** [comment]
```
Running "jsonlint:all" (jsonlint) task
>> File "build/tmp/data/translations/id/terms.json" failed JSON validation. 
Warning: Parse error on line 83:
...pe Tampilan Waktu",+	"SettingsTimeRemai
----------------------^
Expecting 'STRING', got 'undefined' Use --force to continue.
Aborted due to warnings.
```

**Comment by McDohl** [comment]
lel extra "+"

**Comment by freezebear** [comment]
too much "+" =w=;

**Comment by McDohl** [comment]
I fixed this already, its kay

**Comment by freezebear** [comment]
hue.. thx.. =w=;

**Comment by ethrundr** [comment]
Travis-chan is on tsundere mode again..... XD

**Comment by McDohl** [comment]
hue now we get another error from @ReiFan49 
264   build/tmp/pages/strategy/tabs/ships/ships.js
265    386 |                    });
266                              ^ Don't make functions within a loop.

**Pull request merged**
