### PR TITLE
Fixed WhoCallsTheFleet_items

### PR DESCRIPTION
**Pull request by Nishisonic**
|name|changes|
|:-|:-|
|艦本新設計 増設バルジ(大型艦)|change Musashi Kai 2|
|増設バルジ(大型艦)|add Musashi Kai 2|
|32号対水上電探|mix Ise and Ise Kai 2|
|15.5cm三連装副砲|change Musashi Kai 2|
|41cm連装砲改二|fix guaranteed success resource|
|21号対空電探改|change Musashi Kai 2|
|15.2cm単装砲|change Kongo Kai 2|
|九五式爆雷|add Naka Kai 2|
|32号対水上電探改|mix Ise and Ise Kai 2|
|41cm連装砲|add Mutsu Kai 2|
|試製41cm三連装砲|fix Mutsu Kai 2(Tuesday)|
|25mm連装機銃|add Kinu and Kinu Kai|
|三式弾|fix guaranteed success resource|
|F6F-3|mix Saratoga, Saratoga Kai and Saratoga Mk.II|
|25mm単装機銃|add Kinu and Kinu Kai|
|12.7cm連装砲D型改二|remove Yugumo|
|15.5cm三連装砲|fix Mogami can't updated|
|33号対水上電探|add Yubari|
|12.7cm連装砲A型|fix `The amount of material required for updating is different by the second ship`|

### CODE REVIEW

**Comment by sinsinpub** [comment]
👍 it's greatly appreciated for your verifying works on it, にしさん!
but i suggest to open this PR directly on its upstream repo: [WhoCallsTheFleet](https://github.com/TeamFleet/WhoCallsTheFleet/issues) (the real DB repo is: [WhoCallsTheFleet-DB](https://github.com/TeamFleet/WhoCallsTheFleet-DB)), so that more downstream projects (including us) can be benefited.
ps. 中華系作者ですがこのプリのように英語でもおーけーだと思います

**Comment by Diablohu** [comment]
I will review all the changes mentioned above and make changes to https://github.com/TeamFleet/WhoCallsTheFleet-DB

**Comment by Nishisonic** [comment]
Thanks, I re-issue PR to WhoCallsTheFleet-DB.👍

**Comment by Nishisonic** [comment]
https://github.com/TeamFleet/WhoCallsTheFleet-DB/pull/8

**Pull request merged**
