### PR TITLE
[#831] Untested -- Attempts to remove minus sign on remaining time/ex…

### PR DESCRIPTION
**Pull request by ReiFan49**
i just... oh forget it.

again >->o

### CODE REVIEW

**Comment by nekoworkshop** [comment]
`KC3SortieManager.hqExpGained * (ConfigManager.hqExpDetail==1?-1:1)`

Always something new to learn everyday :3

**Comment by ReiFan49** [comment]
if i remember, hqExpDetail with value 1 is "remaining", so a minus would be a good thing to be put (previously) :3

**Comment by dragonjet** [comment]
I was like, :open_mouth: 

ss 2015-09-12 at 07 58 05

**Comment by ReiFan49** [comment]
a mistake that summons another branch _(:3

**Pull request merged**
