### PR TITLE
Change FCM to fish counter during fish events + split mamiya & irako in tooltip.

### PR DESCRIPTION
**Pull request by Tibo442**
When player has at least 1 mackerel: show mackerel counter
When player has 0 mackerel (eg, outside of events): show FCM counter

Also split up mamiya and irako counter in hover

image

### CODE REVIEW

**Comment by sinsinpub** [comment]
a suggestion: might replace the 1st class medal instead? it seems also an event thing, and 'useless' :joy:

**Comment by nonsensed** [comment]
This is just a side note and it doesn't really matter, but we do have some inconsistency between referring to the fish as `Saury` or `Mackerel` or `Mackerel Pike`. Might have to take a close look later on.

I use `saury` in translations because it's more accurate as far as I know.

**Comment by sinsinpub** [comment]
@nonsensed u could just update them in `useitems.json`. don't care internal naming 😂

**Comment by nonsensed** [comment]
Yeah, I know. xD I mentioned it for a slightly different reason.

**Pull request merged**
