### PR TITLE
Adding new maps in eventBattle submission and new fields in spAttack submission

### PR DESCRIPTION
**Pull request by Divinity123**
See the descriptions of the commit messages.

### CODE REVIEW

**Comment by sorewachigauyo** [comment]
The `spattack` changes look okay, but I am a bit hesitant about extending `eventbattle` to normal world maps. The implementation looks okay and I don't believe there are any filters on the API side to prevent normal world submersion. Though, other than it going against the naming, at design, I aimed for the following for `eventbattle`:

1) Having a lighter memory footprint than `abnormaldamage` for the purpose of storing and analyzing battle data in event maps
2) Able to be easily implemented by different KC viewers, with minimal to no adjustment after inception for low upkeep
3) Ease of maintenance to dump data on an event-by-event basis if needed.

This local change does not mean that EO has to accommodate this submitter change. I understand that this change might allow you to collect more data for LB analysis, but I am not so sure about the futureproofing.

**Comment by Divinity123** [comment]
I do agree with your points.
The intention fourinone and I have is to record samples with LBAS in normal maps for a reasonably short duration just to accumulate enough samples for us to validate our LBAS hit rate formula. Since we already have the code for `eventbattle` submission, we might as well use it.

If we do want to keep `eventbattle` for event maps only, I propose to create another table in TsunDB to store 'scratch data'. The idea is that we may want to collect data from specific nodes/maps in normal worlds for validation projects from time to time. And we can make submissions to this table for that purpose.
To keep the submitter simple, we can use the same code as that for `eventbattle` and change the filter at the beginning (maybe add a tag to indicate which validation project the submission is for).

In the long run, I do think a submitter similar to `eventbattle` can help validation projects greatly, as it makes data more accessible (as opposed to single attacks only in `eventaccuracy`). Projects like LBAS hit rate formula and CF targeting logic won't have been possible without the raw APIs we have access to.

Please let me know what you think.

**Comment by sorewachigauyo** [comment]
The proposal sounds good to me with regards to futureproofing and storage duration.

We actually have an existing but unused table `gunfits` with validators for each [gunfit test](https://github.com/Tibowl/TsunTools/blob/master/config/gunfits.json) so there is precedence for such a system. Perhaps you can come up with a proposal of the validation system and we'll discuss more details from there.

**Comment by Divinity123** [comment]
Sorry for the late reply, I had a few really busy days. I have reverted the changes in `processEventBattle`.

As for a new validation system, I am thinking about a system that is similar to `eventBattle`, where the whole rawapi is submitted to TsunDB and the validator(s) can then process the data locally. We only need to change the submission conditions when we need to run one such validation project.
In my opinion, it has the following benefits:
1. Easy to maintain on the backend.
2. Flexible for different validation projects, i.e. we don't have to write a new submitter every time.
3. Full data availability (we could not use the majority of NagaMutsu touch submissions because of the absence of HP information for example).
Ideally, we only need to turn on this submitter for one or two updates for each validation project. The data can then be downloaded by the validator(s) and deleted from TsunDB. We will need to figure out another way if the submitter takes a lot more space than expected on TsunDB.

**Comment by sorewachigauyo** [comment]
Oh, by validation system, I meant validation for the submission conditions. Otherwise, that plan looks good to me. 

Should we proceed with this PR first then?

**Comment by Divinity123** [comment]
To clarify, is your intention to use `eventbattle` for additional validation projects? I think creating another table for those is better because it is easier to maintain. I don't think we should use fine-grained submission conditions in this case as the memory footprint can be quite large.

I am happy to go with the PR for `spattack` for now.

**Review by sorewachigauyo — APPROVED** [review]

**Comment by sinsinpub** [comment]
[84a334c] slightly adjusted 'location' for some properties, plz check if there is problem @Divinity123 
since i guess `fleetType` should not be belonged to ship context, so moved it to `misc` obj.
but actually there should be 2 fleet types, one for player, one for enemy (combined flag only).
anyway for now u can get combined flag from eposititon if targeted enemy is > 6?

**Comment by sinsinpub** [comment]
another thing about amount of player fleet ships to clarify, for vanguard formation, when 1 or more ships sunk or retreated (FCF) during mid-sortie, will the ship amount and ship position be changed in the next battle?
afaik, FCF doesn't affect ship array length, nothing changed; sunk ship disappears from array in the next battle, should affect vanguard.

**Comment by Divinity123** [comment]
> [[84a334c](https://github.com/KC3Kai/KC3Kai/commit/84a334c8e334e4fe7353f7f4899e773514b49082)] slightly adjusted 'location' for some properties, plz check if there is problem @Divinity123 since i guess `fleetType` should not be belonged to ship context, so moved it to `misc` obj. but actually there should be 2 fleet types, one for player, one for enemy (combined flag only). anyway for now u can get combined flag from eposititon if targeted enemy is > 6?

Thanks for the changes. I structured the properties in this specific way to make them compatible with [`eventaccuracy`](https://github.com/KC3Kai/KC3Kai/blob/84a334c8e334e4fe7353f7f4899e773514b49082/src/library/modules/TsunDBSubmission.js#L1449). More specifically, the properties should be structured as follows:
- Ship HP (`hp`)/ max HP (`maxhp`) are [separate entries](https://github.com/KC3Kai/KC3Kai/blob/84a334c8e334e4fe7353f7f4899e773514b49082/src/library/modules/TsunDBSubmission.js#L1405) (`eventaccuray` has ship HP as `attackerHP`, I used 'hp' in my own code)
- Ship position takes the shape [[`fPos, fCount, ePos`](https://github.com/KC3Kai/KC3Kai/blob/84a334c8e334e4fe7353f7f4899e773514b49082/src/library/modules/TsunDBSubmission.js#L1467)]. We do want `eCount` if the enemy is in vanguard formation, but we can get all the data from `eventbattle`.
- Fleet type belongs to [`ship`](https://github.com/KC3Kai/KC3Kai/blob/84a334c8e334e4fe7353f7f4899e773514b49082/src/library/modules/TsunDBSubmission.js#L1449)

We do not need an extra flag for enemy CF as `formation[1]` includes that information.


> another thing about amount of player fleet ships to clarify, for vanguard formation, when 1 or more ships sunk or retreated (FCF) during mid-sortie, will the ship amount and ship position be changed in the next battle? afaik, FCF doesn't affect ship array length, nothing changed; sunk ship disappears from array in the next battle, should affect vanguard.

I think you are right about this. This can be fixed if we use `api_f_nowhps.length` or something similar from the raw API to deduce `shipCount`.
The number of samples we have with sunk ships is small enough such that it has not affected our analysis yet, but it is always a good idea to use the right thing for futureproofing.

**Comment by sinsinpub** [comment]
ok, will revert struct back to compatible with old

**Pull request merged**
