### PR TITLE
Add VERSION param to card.swf

### PR DESCRIPTION
**Pull request by sinsinpub**
#1030 

* Hack card.swf to support version, drag and image switch (with wheel)
* Change `embed` to `object` to catch mouse event, but menu appears...

is this acceptable?

ps. seems mstgear pic not required version...

### CODE REVIEW

**Comment by dragonjet** [comment]
I also updated card.swf to load `?VERSION=` on ship CGs via the newly passed `?ver=` to the embed src

**Comment by dragonjet** [comment]
Checked the new master viewer. It preloads the ship CG so when you visit her in-game, you see the images instantly, no more loading.

**Comment by dragonjet** [comment]
@LostLogia4 might be interested to see

**Comment by sinsinpub** [comment]
oh... but I add other stuffs as: move by dragging and switch image by wheel :sweat: 
like this:
image

I didn't found the source of card.swf, so I hacked the ActionScript with decompiler...
would u mind to add some codes like this?
```
stop();
asd.loadMovie("http://" + (!sip?"125.6.189.247":sip) + "/kcs/resources/swf/ships/" + shipFile + ".swf" + (!ver?"":"?VERSION=" + ver));
onEnterFrame = function()
{
   if(abyss == 0)
   {
      if(asd._currentframe == 4)
      {
         asd.gotoAndStop(4);
         asd._x = 0;
         asd._y = 0;
         var meo = new Object();
         meo.onMouseDown = function()
         {
            asd.startDrag();
         };
         meo.onMouseUp = function()
         {
            asd.stopDrag();
         };
         meo.onMouseWheel = function(delta)
         {
            asd._x = 0;
            asd._y = 0;
            if(delta > 0)
            {
               var _loc2_ = asd._totalframes - 6;
               _loc2_ = _loc2_ < 11?11:_loc2_;
               if(asd._currentframe < _loc2_)
               {
                  asd.gotoAndStop(asd._currentframe + 1);
               }
            }
            else if(delta < 0)
            {
               if(asd._currentframe > 4)
               {
                  asd.gotoAndStop(asd._currentframe - 1);
               }
            }
            
         };
         Mouse.addListener(meo);
         loadinglbl._visible = false;
         delete onEnterFrame;
      }
   }
   else if(abyss == 1)
   {
      if(asd._currentframe == 10)
      {
         asd.gotoAndStop(10);
         asd._xscale = 40;
         asd._yscale = 40;
         asd._x = 0;
         asd._y = 0;
         var meo = new Object();
         meo.onMouseDown = function()
         {
            asd.startDrag();
         };
         meo.onMouseUp = function()
         {
            asd.stopDrag();
         };
         meo.onMouseWheel = function(delta)
         {
            if(delta > 0)
            {
               asd._xscale = asd._xscale + 4;
               asd._yscale = asd._yscale + 4;
            }
            else
            {
               asd._xscale = asd._xscale - 4;
               asd._yscale = asd._yscale - 4;
            }
         };
         Mouse.addListener(meo);
         loadinglbl._visible = false;
         delete onEnterFrame;
      }
   }
   
};
```

**Comment by dragonjet** [comment]
oh didn't notice that, thanks~ :+1: 
I should probably add the flash file on project root next time
I'm also making corrections on `mstupdate.js` where `?ver=` is not yet passed.
gonna push all in a bit

**Pull request merged**
