### PR TITLE
Update gunfit.json with new values

### PR DESCRIPTION
**Pull request by mikenzb**
See #1889, Remaking PR to include added changes

### CODE REVIEW

**Comment by sinsinpub** [comment]
TODO list
 * [ ] Update natsuiro panel activity to show new data
 * [ ] Compute and show accuracy sum of multiple main guns
 * [ ] Take married ship bonus in account

(btw, i'm enjoying MHXX for most free time, will be slow 😹

**Comment by ethrundr** [comment]
Since @sinsinpub add a Todolist to this PR, I'm switching the status from review back to WIP.

**Comment by Tsubakura** [comment]
I have edited the values again for the fit gun based on the new data we had received. Keep in mind that this will be updated regularly both by Sao on reddit and me through wikia, I'll give you a ping if it needs updating again.

**Comment by mikenzb** [comment]
Updated with new values, thanks for the ping @Tsubakura

**Comment by Tedster59** [comment]
is this able to be merged now?

**Comment by mikenzb** [comment]
Nope @Tedster59, still waiting on a few things (see to do list)

**Comment by nonsensed** [comment]
Hmm so is this going to stay dead?

**Comment by mikenzb** [comment]
I've updated the gunfit values again in case anyone wants to work on this, otherwise I'll update the values again in a few months.

**Comment by sinsinpub** [comment]
rebased onto `update-cumulative`, get the idea to redesign the panel activity now, working on it.

**Comment by sinsinpub** [comment]
but i saw wikiwiki page says marriage coefficient (-40%) also applied to plus bonus for ITA guns...?

**Pull request merged**
