### PR TITLE
Test

### PR DESCRIPTION
**Pull request by Agc0de6**
Checkin' mismatches

### CODE REVIEW

**Comment by dragonjet** [comment]
hm `Line 282`, use `"` instead of `“`

**Comment by ethrundr** [comment]
Travis-kun in action XD

**Comment by nekoworkshop** [comment]
Interesting. I thought only Chinese and Japanese programmer were having problem with the randomly poped up curly quotes.

**Comment by Agc0de6** [comment]
@nekoworkshop all UTF users are havin' this troubles

**Comment by nicky008** [comment]
@Agc0de6 That's why I use the local UTF font as a default font for displaying in Chrome. :v

**Comment by Agc0de6** [comment]
@nicky008 this quotes was autmatically places by Google Docs

**Pull request closed without merging**
