### PR TITLE
Hotfix 31.5.2

### PR DESCRIPTION
**Pull request by Vultren**
### ⚓️  Enhancements & Fixes

* #1992 Improve Akashi Repair timer display
  * Move repair time tooltip down
  * Fix Akashi repair timer output if start time is unknown
* #1991 Update styles for DMM site play mode
  * Fix background image size not cover issue (#1824)
  * Take top margin and zoom scale into account (#1989)
  * Add a setting to customize CSS of DMM top page

### ⚓️  Translations & Data

* Add 4th Anniversary Lines
* `en` quotes
* `en` terms
* `jp` terms
* `th` quotes
* `ru` ships

### CODE REVIEW

**Comment by sinsinpub** [comment]
why not follow `fixes -> master -> webstore` flow...? 😓 
btw, also push the workaround to user on #1991

**Comment by Vultren** [comment]
Well I didn't want to mess up a hotfix by adding extra stuff again and this was only for the limited seasonal lines. normally I would do it the normal way of master -> webstore

**Comment by sinsinpub** [comment]
only update TL pointer also possibly mess up by extra stuff :joy:

**Comment by Vultren** [comment]
All this really does is update the pointer. well close this if you want and we'll push it along with the CSS and akashi timer

**Pull request merged**
