### PR TITLE
Add external backup to Dropbox service

### PR DESCRIPTION
**Pull request by reinforce**
Add ability to upload/download kc3data files directly to/from Dropbox storage.
This can be useful for external backup and sync via different devices.

Basically this is a simple Dropbox client which uses REST API.
You need Access Token to use this feature. See the help section to learn how to get it.

For now sync can be done semi-automatically:
 * Export data to file in "Local Backup"
 * Select file for uploading in "External Backup"

And it would be uploaded to Dropbox
And back:

 * Download file from list
 * Import data in "Local Backup"

Related to #17
screenshot at 2017-03-14 13 33 13

Signed-off-by: Aleksei Mamlin <mamlinav@gmail.com>

### CODE REVIEW

**Comment by reinforce** [comment]
@sinsinpub I'll prepare some changes to simplify import/export.
As for ajax methods - not all features work as i wish, but I'll try again.

**Comment by reinforce** [comment]
Seems jquery ajax did not support binary transport(`dataType = "blob"`) out the box. That's why I have troubles with downloading using ajax. Any suggestions?

**Comment by sinsinpub** [comment]
hmm... that's XHR level 2 feature? no clue if latest jquery has given a official solution or not, formerly ppl have to extend jquery's `ajaxTransport` to support handling binary data. eg: https://github.com/henrya/js-jquery/tree/master/BinaryTransport

**Comment by reinforce** [comment]
That's jquery bug. Fixed in newer 2.2.x releases. Tested with jquery-2.2.4.min.js.

**Comment by Tedster59** [comment]
I'm guessing this is basically dead right now?

**Comment by reinforce** [comment]
Work completed, but I recreated origin branch and it stucks on checkings. If anyone still interested - I'll create new pull request.

**Comment by sinsinpub** [comment]
@reinforce yep, could open a new PR 😆

**Comment by mikenzb** [comment]
PR has been closed due to the master branch being reverted, reopen a new PR if this feature is still being worked on.

**Pull request closed without merging**
