### PR TITLE
try caching npm dependencies

### PR DESCRIPTION
**Pull request by Javran**
see: https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies

### CODE REVIEW

**Comment by sinsinpub** [comment]
haha, i just wanna test if this could speed up (travis really slow now), seems stuck at patch waiting for interactive 😅 
image

...revert it for now.

**Comment by sinsinpub** [comment]
after adding `if` and dry run test to the patch command line:
```batch
- if ! patch -R --dry-run -s -d node_modules/grunt-contrib-uglify -p2 < misc/uglify-harmony.patch; then patch -N -d node_modules/grunt-contrib-uglify -p2 < misc/uglify-harmony.patch; fi
```
seems speed up 30s 😂 
image

**Comment by Javran** [comment]
@sinsinpub sounds like it's working now?

**Comment by Javran** [comment]
@sinsinpub the change doesn't seem to be in master branch, maybe open a new PR for it?

**Pull request merged**
