### PR TITLE
[dev-tp-calc] New TP calculation for event

### LINKED ISSUE #1324: TP calculation
we can do TP calculation when using transport escort combined fleet this might be useful for the coming event.

related documents:

- [Wikia: Events](http://kancolle.wikia.com/wiki/Events)
- [WhoCallsTheFleet TP calculator](http://fleet.diablohu.com/calctp/)

I don't have much time working on this before the event, so feel free to take over if you are interested.

### PR DESCRIPTION
**Pull request by sinsinpub**
May close #1324 
Picked from PR #1268 (branch `dev-api-2`) and credits to @ReiFan49 
(merging 1268 may cause github automatically merge this)

Feature summary:
 * New TP calculation for this event, a possible TP value range for BOSS Rank A to Rank S will be obtained on the landing node and shown on battle activity of panel
 * And the TP value range also appears as a tool-tip of combined fleet summary on panel
 * TP multiplying parameters can be maintained in `tp_mult.json`, and it's possible to be live updated
 * Extra changes:
   * Prevent blinking of map gauge instead total disabling
   * overlodger minor fix, may integrate with PR #1329

### CODE REVIEW

**Comment by dragonjet** [comment]
ah perfect I didn't know there was a feature like this on that branch

**Comment by dragonjet** [comment]
do we need further testing for this?

**Comment by sinsinpub** [comment]
more testing always better...
but I guess someone would like a TP calculator when setting the fleet before sortie :laughing:

**Comment by ReiFan49** [comment]
TP Calculation can be performed at anytime, by performing `obtainTP` for every ships. While doing `add` at `obtainTP` objects might add another TP from another `obtainTP` or `KC3Meta.tpObtained` for it's base calculation

**Comment by sinsinpub** [comment]
got that, could try to add the 'predicted' TP value to panel when fleets combined to transport type.

**Comment by dragonjet** [comment]
thanks for following up on this, you guys can merge when ready :+1:

**Comment by ReiFan49** [comment]
wait... why i pressed close lol... somehow this lag is funny

**Pull request merged**
