### PR TITLE
LBAS Interface

### PR DESCRIPTION
**Pull request by dragonjet**
* show airbases in the F12 panel
  * airbase name, range, fighter power, intercept fighter power, intercept bomber power, action
  * list of planes for each airbase
    * image, icon, proficiency, slot count (red if not full), morale condition
* Contains updates to libraries to allow calculation of interception power against fighters and another against bombers

ss 2016-08-14 at 04 39 33

### CODE REVIEW

**Comment by dragonjet** [comment]
@KC3Kai/testers if you can switch to this branch and test it our, would be nice :+1:

**Comment by paulogabbi** [comment]
first time to post here so sorry if i made some mistake

i have find 2 "bugs"
 
one of my planes is not loading

and you can see in this picture https://gyazo.com/8de69ec4282a51536c5843f50b9ca2bd the plane count is not updating after the resuply

**Comment by dragonjet** [comment]
@paulogabbi thanks for testing :+1: can you specify which plane that is? I just manually download the plane images so I might have missed some XD

thanks for the resupply reminder, this is not yet supported at the moment but will do them soon

**Comment by paulogabbi** [comment]
@dragonjet the plane in question is the http://kancolle.wikia.com/wiki/Type_96_Land-based_Attack_Aircraft

**Comment by paulogabbi** [comment]
find 2 new bugs

the first is a inverted plane in the LB screen

the second is if the plane don't have a ranking the screen show a missing img 

you can see the bugs in this screenshot http://puu.sh/qBUwu/9c66ec8685.jpg

**Comment by mikenzb** [comment]
Bug: 3rd Airbase is not shown? LBAS supports 3 land bases and supported 3 last event as well so seems kinda odd my 3rd base isn't loading.
capture

Also missing some LBAS plane images as well for [Ginga](http://kancolle.wikia.com/wiki/Ginga) and [Type 1 Land-based Attack Aircraft Model 34](http://kancolle.wikia.com/wiki/Type_1_Land-based_Attack_Aircraft_Model_34)

Feature request: Name shown of planes when mousing over the planes would be nice.

**Comment by dragonjet** [comment]
@mikenzb I've just supposedly fixed the error you got. Can you checkout the latest `dev-lbas-ui` and see if you don't get warning now? I don't have the new planes that you have there so I can't test XD

**Comment by HKGPsy** [comment]
In the current UI, the interceptor power are separated as against fighters and against bombers.

In practice, the more important features would be the overall interceptor power so that we can calculate how much we need to get a sufficient power for AS+ (e.g. 16 Autumn event E5). Would similar feature be included in the upcoming major version 31.0.0? Sorry if I have asked a redundant question.

**Comment by dragonjet** [comment]
@HKGPsy good insight, can you also post this as a new issue if it doesnt exist yet? just to have it noted under the open list

**Pull request merged**
