### PR TITLE
Deduplicate Image Export

### PR DESCRIPTION
**Pull request by Adrymne**
Refactor image output logic from `Screenshot`, `ShowcaseExporter` and `sortielogs` into new module `ImageExport`.

---

Mentioned this in #1942, but I suspect it might be a good idea to modify Settings so the player can choose to exclude certain output methods (or maybe just remove `saveImgur` as a fallback method). I could use some help with the UI design though; experience has taught me that particular area is not my forte.

### CODE REVIEW

**Comment by DynamicSTOP** [comment]
This PR make me think that i have to start learning ECMA6 :rofl: i an not skilled enough in it to make a review.

**Comment by Adrymne** [comment]
I can dial back the ES6 if it's an issue, most of it is just sugar. I do need Promises though - my first attempt using callbacks got messy in a hurry. As it is, the code should be fairly robust, even if it is kind of ugly.

(Ironically, I spotted a bug regarding ajax error handling as I was typing this.)

I could probably do better with async/await or co.js, but the former is too recent (Chome 55) and I don't know what the policy on including new libraries is for the latter.

**Comment by DynamicSTOP** [comment]
Nah, es6 features should stay. Supporting es6 was discussed here #1698  and if i'm not mistaken everyone was ok about it. It's just i who need to learn it :rofl:

**Comment by Adrymne** [comment]
I'll probably do some rebasing tomorrow. The end result shouldn't change, but b319b71 should really be three separate commits: "De-duplicate to new module" + "Implement output fallback" + "Prevent new tab from grabbing focus".

**Comment by Adrymne** [comment]
This ended up being a bit more substantial than the quick rebase I expected. Changelog:

- Fix Image Quality setting not being properly applied
- Fix unable to download image from "New Tab" mode
- Split "De-duplicate image export logic" into "De-duplicate image export" (d535f95), "Add image export fallback" (3576a0d) and "Prevent new tab from grabbing focus" (59a7d02).
- Rewrite `ImageData` as the factory function `composeImageData()`
- Implement `writeToCanvas()`, which creates a canvas loaded with the contents of a dataURL specified by the caller (data encoded via steganography is not lost).
  - Drop support for dataURLs as input to `KC3ImageExport`, since the use-case is no longer valid.
- Modify Imgur upload to use a Blob instead of a dataUrl
  - Drop support for outputting a dataUrl from the canvas, since the use-case is no longer valid.

@DynamicSTOP Turns out the issue with the Blob upload was `$.ajax()` was setting the incorrect `Content-Type`.

**Comment by ethrundr** [comment]
I'll try merging #1960 now.
If Travis persist, then you should debug your own code: there is an error.

**Comment by Adrymne** [comment]
I have no idea what's going on any more, so I'm just going to stop here and hope someone more experienced with git/Travis can figure out what's wrong.

**Comment by Tedster59** [comment]
apparently it worked, so should I merge?

**Pull request merged**
