### PR TITLE
badge generator location change

### PR DESCRIPTION
**Pull request by Vultren**
Following up on #1832. working with @Nya-chan to keep the badge generator updated.

### CODE REVIEW

**Comment by Javran** [comment]
just a reminder that http://www.sanya.moe/kcbadge now only supports English, if you switch to another language there'll be error message saying `Can't find DB, please contact Ryuuhou Kagiyama on Himeuta.net` that should be fixed before we can proceed to merge.

**Comment by Vultren** [comment]
Wait, really? ok, let me check that out tomorrow, and if the problem is what I think it is, it should be fixed in the Zara Kai Ni Update

**Comment by Nya-chan** [comment]
Just notifying that the last time I tried, the page couldn't get the post data, not sure the server has it sorted already and should be tested first.

**Comment by Vultren** [comment]
there was a comma missing before CT that was causing the problem, I'll change the issue number in a few hours

**Comment by dragonjet** [comment]
@Nya-chan @Vultren once this is ready, let us know so we can merge.

I'd also like to add you in the about page, as the original `ThreeBards.com` has an entry in the partners section. Would you like to be added separately as fork developers or under the partners tab as one entry for `sanya.moe`?

**Comment by Nya-chan** [comment]
@dragonjet I have no problems with being mentioned there, you can go on with that~ Not sure what is the difference, so whichever is more fine with you, I guess?

**Comment by Javran** [comment]
on an unrelated note, I wanna point out that I-26 is of the same class as I-19, so they are supposed to be categorized under same class.

**Comment by Nya-chan** [comment]
Just a note that this should be ready to go shortly - it probably worked already, because I was stupid and was testing with sanya.moe instead of www.sanya.moe (like Vultren properly uses) and because of permanent redirect I wasn't getting proper POST data - one always learns that laziness doesn't pay off.

I'll just update the link to lead into github fork, since there's no point to direct people to report problems in a forum thread anymore.

**Comment by Javran** [comment]
@Vultren @Nya-chan btw I feel something is slightly messed up across different languages:

- all Winter 2017 ship appear only in en
- Iku and Nimu are grouped together in non-ens but in en they are still separated

also some problem in Poster Collection related to remodel chain:

- Fujinami Kai doesn't seem to toggle Fujinami on (same problem goes with Asakaze Kai, Matsukaze Kai, Zara Due, I-13 Kai, I14 Kai)
- Saratoga icon not toggled on

Before testing this branch I've already remodelled all ships except Saratoga so not sure whether they have been supported in the first place.

**Comment by Vultren** [comment]
@Javran is this all in the non-en versions?

**Comment by Vultren** [comment]
ok I see what you mean with the toggle, that was me trying to get the update in before I went to work. that's an easy fix. Sara's in the conversion json though...... And I just now understood the "mstId2FleetIdTable" field in the conversion json. and Sara's entry is missing a one. the non-en on the other hand, that's going to take a bit of work. This was a problem before I took over the updates.

**Comment by Javran** [comment]
those problems that I pointed out can have their own separated issue in k2badge repo. now that every language is working so I see no problem merging this.

I intended to open a new issue to put my comments there but got a bit confused: there are 2 forked repos from original author: https://github.com/Vultren/k2badge https://github.com/Nya-chan/k2badge but which one is supposed to be the main branch?

**Comment by Vultren** [comment]
Stick the issues in mine. I'll be doing most of the updates

**Comment by Javran** [comment]
since this PR has received some approvals I'm going to merge this. 
for problems that I've pointed out, they will be tracked by https://github.com/Vultren/k2badge/issues/2

**Pull request merged**
