### PR TITLE
Refresh Reminder

### PR DESCRIPTION
**Pull request by HitomaruKonpaku**
Just a reminder

image

image

### CODE REVIEW

**Comment by HitomaruKonpaku** [comment]
You mean the group header term?

**Comment by sinsinpub** [comment]
yeah, all related terms.
the key point of shrinking memory footprint is 'close and reopen the devtools (termed by 'Panel' or 'Info panel' in our terms)', or restart the game and kc3 panel entirely.
should clarify it: not only refresh game page, nor refresh kc3's panel. it's completely reload all the panels of devtools.

**Comment by HitomaruKonpaku** [comment]
Can you help me update those term? Don5 have pc right now to update it

**Comment by mikenzb** [comment]
AHHHH wrong branch lol... whoops

**Comment by sinsinpub** [comment]
and u forgot the translation pr 😂

**Pull request merged**
