### PR TITLE
Fix #796

### PR DESCRIPTION
**Pull request by bcc32**
Added a missed comma, which was causing travis-kun to complain.

### CODE REVIEW

**Comment by bcc32** [comment]
I've based this commit on my earlier patch commits rather than on the branch with the revert.  Let me know if you want a rebase.

**Comment by McDohl** [comment]
no need, travis kun is now pleased :+1:

**Comment by McDohl** [comment]
no need, since travis kun is now pleased xD

**Comment by dragonjet** [comment]
let me just tag this here #796 XD
making changelogs

**Pull request merged**
