### PR TITLE
Patch 31.0.3

### PR DESCRIPTION
**Pull request by dragonjet**
### Fixes and Adjustments
* Fix Strategy Room graphs infinite loading - Part II
* Graphs fill color on label boxes on tooltips
* #1656 Fix devtools opens `about:blank` pages instead of Strategy Room
  * In "Gun Fit" activity notice, click on the colored fit box to go to Ship page

### Notes
For full information about the changes in Version 31 see the entry "Release 31.0.0"

Alternatively, you can [click here to view the full page](https://github.com/KC3Kai/KC3Kai/pull/1789).

### CODE REVIEW

**Comment by CPAVELSKI8** [comment]
image

hiya! not sure why. but when i try to launch the game through any option, i get sent to the server select screen and clicking on any of them gives me the error screen. any way to fix this?

**Comment by dragonjet** [comment]
@CPAVELSKI8 are you sure you are logged in to the correct account? or is it that you are just starting to play the game?

if you're a new player please read the wikia on how to register with the game. if not then just try to logout and log back in.

**Comment by CPAVELSKI8** [comment]
@dragonjet Yes im sure. Im using a new computer and this is what ive been greeted to. The game works flawlessly on my laptop but not on my new desktop.

**Comment by dragonjet** [comment]
@CPAVELSKI8 can you try disabling the extension on your new computer, and re-trying playing the game on DMM website and see if it's the same?

**Comment by CPAVELSKI8** [comment]
@dragonjet Tried with and without VPN. Also tried it with the extension disabled and then with it uninstalled completely. Still getting sent to the server select screen and crashing when selecting any server.

**Comment by CPAVELSKI8** [comment]
@dragonjet 
image

Might be helpful if i post an image with the error

**Comment by mikenzb** [comment]
Seens very odd, you did log out and log into the correct account right? also try setting your time to GMT +9 (Tokyo) to see if that has any effect otherwise u can also try clearing cache and cookies as well.

**Comment by CPAVELSKI8** [comment]
@mikenzb do i have to sync the time change or simply change the clock?

**Comment by mikenzb** [comment]
Changing the system time to Tokyo should do it.

**Comment by CPAVELSKI8** [comment]
@mikenzb Worked! Thank you so much!

**Pull request merged**
