### PR TITLE
[dev-rank-predict] Battle rank prediction

### PR DESCRIPTION
**Pull request by sinsinpub**
About #728 

It's not my branch ofc :smiley:
I just add the prediction result to battle panel and created this PR, hoping this feature could be released earlier.
@KC3Kai/testers or anyone who interest in could try this branch and report the accuracy of prediction. any question, @Javran
Ofc rank prediction is able to switch on/off via Settings.

Final summary:

* Battle rank prediction: show the rank at the same position with real rank of battle activity panel, with 50% opacity. And a setting item added to switch this prediction on or off.
* Show MVP icon: show a small MVP icon on ship face of sent fleet as soon as battle result screen displayed.
* A workaround of KO stamp on PvP: Show KO stamp even if ship HP left 1.
* Update content and format of tool-tips on kinds of ship face.

### CODE REVIEW

**Comment by sinsinpub** [comment]
And battle KO/sunk stamp needs help too, @ReiFan49 
I will also try

**Comment by sinsinpub** [comment]
battle stamp problem may solved. just an jQuery mistake...
and make a different text for PvP as it had been supposed to.

**Comment by dragonjet** [comment]
nice good work fixing this @sinsinpub. I thought you were getting the stamp error on main branch so I thought it was something on your side xD never knew it was on this branch

**Comment by sinsinpub** [comment]
@dragonjet it's on master branch (see the 8b24cca diff), I just commit it on this side...

**Comment by sinsinpub** [comment]
Impl. #960, for both sortie and PvP, show:
`Contact:  (or None) vs (or None)`

**Comment by Javran** [comment]
@sinsinpub is contact plane related to battle rank prediction? If not I'll suggest openning another PR for that purpose.

**Comment by sinsinpub** [comment]
@Javran I'm updating Node data collecting and theme displaying... show contact plane just a little modification in passing :sweat_smile:

**Comment by Javran** [comment]
@sinsinpub I think that still worth a single PR, it can at least make you commit land on master branch faster, also I'm afraid to run into things like #1155 where we get too many features in one PR.

**Comment by sinsinpub** [comment]
@dragonjet I think it's ready to merge if no issue reported.
And may left the combined fleet verifying to the event period :smiley:

**Comment by dragonjet** [comment]
tested it on PvP too :+1:

**Pull request merged**
