### PR TITLE
Patch  31.0.7

### PR DESCRIPTION
**Pull request by dragonjet**
### Updates
* Also show F33 tooltip with factors for Combined View
  * Adjust width of summary columns
* Compute enemy air power for researching unknown node
  * Key problem is to guess unknown slot capacity of abyssal ships
  * Hover on air battle condition to see known air power and unknown IDs
  * Should be fail-safe for unexpected input
* Show TP tooltip for all types of Combined Fleet
* Add double click link to ship drop
  * Fix double click data and event cleaning method
* #1825 Exporter: stripped ships from equip stat bonuses (PR #1827)

### Translations and Data
* Update WhoCallsTheFleet DB
* `en` quests
* `en` terms
* `jp` quests
* `th`quests

### Notes

### CODE REVIEW

**Comment by puroidrogeno** [comment]
is quite long time that using DMM on website and API link stuck the game on a withe screen, from the today patch (the only one i can use) DMM on frame reach the game normally i can click everything and hear the sound but all the game is a black screen

**Comment by dragonjet** [comment]
this is in the patch notes
* #1789 Release 31.0.0

in chrome 55+, dmm frame and api link may not work 

more info
* #1645 Merged Gameplay Option
* #1722 New Gameplay Mode

original issues posted during the first chrome mess-up
* #1641 Chrome Version 55: Black screen
* #1643 [Issues] Panel don't start

**Comment by puroidrogeno** [comment]
@dragonjet i write because i think is a new problem, already checked those thread before write, this is how i have the game page using dmm website and api link: https://gyazo.com/b93c4a066eabf2a10f3189a5f4274881

instead using dmm on frame is like the normal game page with sound and clickable things but all is black, i mean i can play but at the same time i can't see what' appening

ch version 56

**Comment by dragonjet** [comment]
@puroidrogeno can you try disabling kc3 (not uninstalling since it will clear your history) just uncheck it from extensions page and see if the same problem persists on dmm website

**Comment by puroidrogeno** [comment]
@dragonjet hey buddy, i tried to clear as you asked, checked again flag/adblock and other stuff following the post on facebook, but still i got a withe screen when i get on kancolle page (i only can see dmm button on top, ads on right side and the glossary under the "game". i think is this version: 56.0.2924.87 causing problem, i just tried on other browser like firefox and the game start perfectly

**Comment by dragonjet** [comment]
@puroidrogeno join us in discord. let us not discuss this in a patch notes thread.

**Pull request merged**
