### PR TITLE
Update maintenance time

### PR DESCRIPTION
**Pull request by reinforce**
Next maintenance scheduled for April 5, Wednesday

### CODE REVIEW

**Comment by sinsinpub** [comment]
eh... i didnot found the official tweet telling the time... is it guessed from history?

**Comment by reinforce** [comment]
@sinsinpub 
Tweet: https://twitter.com/KanColle_STAFF/status/846160963711647744
Wiki thread: http://kancolle.wikia.com/wiki/Thread:543673

**Comment by sinsinpub** [comment]
i mean time of start & end. they only announced the date. i think there is no necessary to rush into updating without start time at least 😂

**Comment by reinforce** [comment]
Well, maintenance start time is mostly the same(11:00), only end time may be changed.
@ethrundr already merged commit, you can revert it if you want

**Comment by ethrundr** [comment]
@sinsinpub mostly recent maintenance has such pattern for the start and end, that's why I merged the commit.

**Comment by reinforce** [comment]
Maintenance end time at 19:00 now confirmed
https://twitter.com/KanColle_STAFF/status/848348406799978496

**Pull request merged**
