### PR TITLE
More i18n support

### PR DESCRIPTION
**Pull request by sinsinpub**
As I mentioned at KC3Kai/kc3-translations#42
I'm working on replacing more hard-coded UI texts with i18n compatible implentations (mainly devtools panel).

I'm playing KanColle with dev build KC3Kai of myself, main codes have been tested.
It's work in progress. Let me know if any problem there I've not realized.

ps. The workaround of `headers.Date` and fixes of some minor problems have been included.

### CODE REVIEW

**Comment by sinsinpub** [comment]
These days I have tried making minimum changes of codes to improve i18n support.
Considering it's just the workaround, looking forward for better implementation or long-range plan.
About the improvement of i18n support and l15n for Japanese, summarize the changes I made:

* For i18n:
    * Replace the hard-coded texts in all js & html files related with `natsuiro` and `plain` theme with corresponding i18n method.
    * Add a new css class `i18n_title` and the processor for the texts in `title` attribute.
    * Add a `format` function to `String.prototype` to make the replacements with values of parameters more convenient.
      It gives translators of other languages the chance to decide the order of words.
    * Move the battle formation texts from `Meta.js` to `battle.json`, so they could be localized.
    * Move the special situation `No Air Battle` to `battle.json` too.
    * Add or adjust the style `white-space:nowrap` to more proper place, prevent line breaking make the looks worse,
      even if the width of glyphs overflow or font rendering has problem.

* For Japanese l15n:
    * Complete and adjust the translations of Japanese text again and again, based on my testing in real game and understanding of source codes.
    * Change the font family of JP to make visual of non-CJK chars to be unified with EN. Less width adjustments will be required in future.

* Other minor fixes:
    * Include `headers.Date` missing problem workaround, two fail-safe UTC time functions have been added to `Date`,
      but not used by Kcsapi yet.
    * Fixed the problem that world map hp gauge is not displayed as `KC3Meta.gauge` requires the map id without `m` prefix.

* New features related:
    * Add more tool tips to panel elements, to show more details of the battle and quests.
      Some great enhancements by others may have been planed, but I think make use of existed info, should be useful for now.
    * A new option is added to settings to force the name of ships and items always display with original Japanese.
      If we can have an option for EN stype, why not for JP ship. Not all people like the translations if they can read JP :smiley:

**Comment by ReiFan49** [comment]
>Fixed the problem that world map hp gauge is not displayed as `KC3Meta.gauge` requires the map id without `m` prefix.

umm it might be clashes with the `dev-api` or `dev-ledger` which is i fixed the same thing too XD

**Comment by sinsinpub** [comment]
:smile_cat: yes it does. but replacements of `KC3Meta.term` make more conflicts...
it does matter if those branches merged, I'll keep on solving.

**Comment by dragonjet** [comment]
should we merge this first or @ReiFan49's #1104 if both will have a conflict? I'm thinking of merging this first, because it can be done directly on github, but if @sinsinpub will do the conflict resolution, ReiFan49 will get the conflict bugs if we merge this first

**Comment by sinsinpub** [comment]
both is ok for me
I'm trying merging two branches locally to see if more translations needed or not

**Comment by sinsinpub** [comment]
have merged `dev-api` branch (included PR #1104)
but seems that something wrong with unit tests itself

**Comment by dragonjet** [comment]
try pull latest master, I added ConfigManager to Master tests

**Comment by sinsinpub** [comment]
finally merged and fixed again. Some conflects need to be verified:
* function `repairTime` in `Ship.js` keeps Javran's, is this ok?
* `_raw` changes of `Master.js` make internal vars like `_ship` not available any more, all their refs updated, but internal usages, such as `updateRemodelTable`, should be verified?

**Comment by Javran** [comment]
@sinsinpub my version of `repairTime` is ok. about changes in Master.js, I suspect more places have to be modified (just fixed ship & equip library), including `updateRemodelTable`. it uses `_ship` but that doesn't exist anymore.

**Comment by sinsinpub** [comment]
including updateRemodelTable. it uses _ship but that doesn't exist anymore.

yes, I have replaced them with `_raw.` one simply in my branch. but left a problem: is it reasonable that add custom properties to the `raw`?

**Comment by dragonjet** [comment]
sorry about that, I thought all was using `.ship()` function

>is it reasonable that add custom properties to the raw?

 like which properties? we can add another `custom` for derived values though.

**Comment by sinsinpub** [comment]
the properties with `kc3_` prefix in `updateRemodelTable` function.

I just found another problem: for clean environment which no `_raw` in localStorage yet, `updateRemodelTable` will fail on devtools open.
`_raw.ship` seems to need checking like this?
```
shipAry = !this._raw.ship ? [] : Object.keys(this._raw.ship);
```
(not commit yet)

**Comment by dragonjet** [comment]
hm if remodel table is sourced from a JS file, we won't need to save it in localStorage - sorry haven't checked those two functions in Master js and currently at office :laughing:

**Comment by ReiFan49** [comment]
sounds like i got missed some of the train lately...
the old `kc3_` variables were meant to simplify the shoukaku and zuikaku remodel tree during that time though, by linearly iterating from the sorted ship list itself

**Comment by ReiFan49** [comment]
[several workaround for people who hates to load `api_start2` like myself](http://puu.sh/npJfA.txt)

**Comment by sinsinpub** [comment]
master and dev-api merged, new item check may work again.
may continue to improve those codes after merging this :smiley:

**Comment by Javran** [comment]
a bit off-topic but I'm just wondering if my RemodelDb (https://github.com/KC3Kai/KC3Kai/blob/master/src/library/modules/RemodelDb.js) is good enough to replace the need of `Master.updateRemodelTable`? they are doing almost the same thing.

also I feel this PR should be prioritized, as commits stack overtime and we might have more trouble keep it sync-ed with master.

**Comment by dragonjet** [comment]
yes I agree, but the blocker at #1104 is near merge, and I will step-in this weekend if needed to get it merged and this one as well. might even go far as merging the ecma6 PR if it's required. here's how I see the pipeline atm:

#1155 i18n needs #1104 ledger
#1104 ledger needs #1170 quest rework
#1170 quest rework needs #918 ecma6

**Comment by LostLogia4** [comment]
@dragonjet that ecma6 PR was long obsolete already, with its code already integrated into pull request #1104.

**Comment by sinsinpub** [comment]
#1104 (and its dependencies) haven been merged (and made some necessary fixes of course), it's safe to merged this and skip #1104

this branch also helps solve `master.js` change problem, it seems @Diablohu committed a incomplete workaround for `ship.js`, which has been solved by this branch.

left discussion mainly on the code style of quest tracing function.

**Comment by Javran** [comment]
if #1155 has merged all patches, I'm good with it as long as it has been tested. issue #1170 can be delayed since it does not change anything on the surface.

**Comment by dragonjet** [comment]
ah I see thanks for clearing this up @all

**Comment by dragonjet** [comment]
but @LostLogia4 you mean #1104 has the ecma6 settings?

**Comment by sinsinpub** [comment]
merging these branches makes confuse, i'm sorry for that :smile_cat:

**Comment by LostLogia4** [comment]
@dragonjet yes, check Kcsapi.js. you know it to be true.

**Comment by dragonjet** [comment]
@LostLogia4 I meant the `.jshintrc` which includes `"esnext": true` is the one that enables ecma6, and is what I was looking at in that PR :laughing: 
https://github.com/KC3Kai/KC3Kai/pull/918/files

**Pull request merged**
