### PR TITLE
node tooltips for resource gain / loss

### PR DESCRIPTION
**Pull request by Javran**
hover on resource / maelstrom nodes to see resource gain / loss on that node.

2017-01-06_174812_3840x1080_scrot

already tested on resource / maelstrom / bounty (1-6 N) nodes.

### CODE REVIEW

**Comment by sinsinpub** [comment]
`api_icon_id` TL...? may be in `battle.json`, or make a new one for `useitems` (tho icon is better

**Comment by Javran** [comment]
@sinsinpub maybe creating a `useitems.json` for it? I definitely prefer if icon can work, but then we'll have to wait until #1718 is solved.

**Comment by sinsinpub** [comment]
useitems names ready, I could replace the names table now.
but strange KC devs, they use different ID values... the mapping table between [icon_id, useitems id] is still necessary

**Comment by Javran** [comment]
@sinsinpub you can take over this branch, I'm going to sleep..

**Comment by Javran** [comment]
LGTM. (can't approve my own PR)

**Comment by Javran** [comment]
I'm merging this since we've got 3 approvals.

**Pull request merged**
