### PR TITLE
replaced  DataURI with Blob in showcase exporter

### PR DESCRIPTION
**Pull request by DynamicSTOP**
Made based on [this so answer](http://stackoverflow.com/a/12300351). Special thanks goes to @Adrymne

1.  It allows to ignore 2 * 1024 * 1024 url size limit for new tab
2.  Browser window resize works WAY faster if Blob used in url instead of dataURI

### CODE REVIEW

**Comment by Adrymne** [comment]
Curious why you didn't use `canvas.toBlob()` - is Chrome 50 too recent?

On a related note, we should probably de-dupe the image export logic.

**Comment by sinsinpub** [comment]
@Adrymne yes, a little. current kc3kai min chrome is supposed to be 49
@DynamicSTOP troll: why use a `*` in title, there is no markdown parsing 😂  will look if there is another method to get blob later.

**Comment by DynamicSTOP** [comment]
@sinsinpub title was taken from first commit message and as for commit messages it's just a habit from project at work.

https://gist.github.com/DynamicSTOP/53c51e12dd56c9d257cef2344f9e2e40
Can't force imgur to use blob. Always error 500, but 500 is server side :\

**Comment by DynamicSTOP** [comment]
Btw where are info about min chrome version hiding? Can't find anything in about\readme.md\manifest.json\webstore page

**Comment by sinsinpub** [comment]
@DynamicSTOP no hard definition at anywhere (#1789 mentioned it), just because some known players still using kc3kai under Windows XP. dj was thinking that set min chrome version for webstore, but

**Comment by Adrymne** [comment]
*Really* should have posted this earlier, but: the contents of this PR will be covered by the fix for #1942.

**Comment by DynamicSTOP** [comment]
I am ok with that. The only thing that worries me is imgur upload. Can't force it to use blob. Keep saying error 500, but it should be something server side.

**Comment by Adrymne** [comment]
I'm having issues with that as well; Imgur was apparently unable to read the blob. In the worst case, we can use the dataUrl as a fallback.

**Pull request closed without merging**
