### PR TITLE
add event map at drop_record in SR and add ship link to ship info page

### PR DESCRIPTION
**Pull request by 107nationalstation**
better UI at drop record page in SR

### CODE REVIEW

**Comment by 107nationalstation** [comment]
related to [issue 1863](https://github.com/KC3Kai/KC3Kai/issues/1863)

**Comment by Javran** [comment]
sounds like you have more plan to do.
just for saving some more PRs, I'll just leave this one open for now, you can continue working on it and let me know when you are done.

**Comment by 107nationalstation** [comment]
@Javran My problem is that I lost all my data of event as a result It's hard to test the event map is cureently added.

**Comment by Javran** [comment]
@107nationalstation don't worry, I can confirm event drops are working fine.
talking about UI itself, however, I'll prefer dropdown boxes rather that the current UI of selecting worlds & maps, it's taking too much space but not doing much: user will alway click ">" several times just to skip regular maps to be able to see event drops, in my opinion it will be much better to just show two dropdown boxes, one for world selection and another for map's. and this leaves more free space for more filtering features (e.g. event difficulty checkboxes, rank checkboxes) to be added.

**Comment by 107nationalstation** [comment]
@Javran Oh dropdown box is better choice thx for your guiding. the online backup feature is the one that I really want , but it's hard to use dropbox in some area. I'll test if it should work to put backup in my vps.

**Comment by 107nationalstation** [comment]
@Javran  now it looks like that

**Pull request closed without merging**
