### PR TITLE
[dev-show-aaci] Show AACI battle flag on panel

### LINKED ISSUE #959: Battle Result: Show AACI
Originally from #889
On battle tab during sortie, show the ship that performed AACI if it was triggered

https://github.com/KC3Kai/KC3Kai/issues/889#issuecomment-142190312
> akizuki (4th ship on slot) performing AACI
```
"api_air_fire": {
  "api_idx": 3,
  "api_kind": 1,
  "api_use_items": [122, 3, 106]
}
```

### PR DESCRIPTION
**Pull request by sinsinpub**
Close #959

For #959 as the comment, I'm adding the AACI icon to the battle flags row of the battle activity panel like this:
image

And two dark theme icon just missing :joy: 

btw this fix the KO stamp for PvP to correct condition, the mistake Ive made on last PR. :sweat_smile:

### CODE REVIEW

**Comment by dragonjet** [comment]
is that 2nd or or 3rd icon? I'm gonna make a new icon

**Comment by sinsinpub** [comment]
@dragonjet 3rd one, see #959#issuecomment-210552579

**Comment by dragonjet** [comment]
ah I see, will use a black AAFD icon. I'm gonna put it on `dev-show-aaci` then merge this once done

**Comment by sinsinpub** [comment]
Notice that abyss ship name translated, so someone wish, shipgirl's `yomi` (the romaji of shipname) could also be translated now :smiley: 

@dragonjet ah, as I forced push a commit, u may need to hard reset ur local branch (or delete old then fetch new) before push the icons.

**Comment by dragonjet** [comment]
oh wait did I do something wrong? I didn't reset the branch before pushing. did you lose commits?

**Comment by sinsinpub** [comment]
@dragonjet np, I rebase this branch onto master for cleaner log graph and TL pointer conflict. It's ready to merge.

**Comment by mikenzb** [comment]
@sinsinpub just noticed something, it doesnt show 2 AACIs was doing 1-6 and it only showed the first AACI, would be nice in the future if it showed more than one AACI and maybe some stats too?

**Comment by LostLogia4** [comment]
@mikenzb Whaddaya mean by 2...? ...oh wait. Air battle nodes has **two** initial airstrikes.

**Comment by mikenzb** [comment]
Yeah didn't get a screenshot but it's something to think about because those air nodes where u have 2 air strikes, the Icon is active when you go into the air node and when I mouse over it it says AACI by Akizuki but during the 2nd airstrike I had Teruzuki AACI and that wasn't noted anywhere.

**Comment by sinsinpub** [comment]
@mikenzb hm which node u get that, we have to reproduce it if there is no battle API json data supplied...

**Comment by mikenzb** [comment]
Does a replay image come with the needed battle data?

**Comment by LostLogia4** [comment]
@mikendb usually it does.
Failing that you can retrieve the api_airbattle from network tab while running 1-6.

**Comment by mikenzb** [comment]
http://i.imgur.com/1EZiKiv.png

**Comment by sinsinpub** [comment]
@mikenzb got it. there is `/api_kouku2/api_stage2/api_air_fire` node for the 2nd one.
but I'm thinking how to represent it with just one flag icon...
maybe just add more tool-tip texts to show like:
```
 1st fire: Terutsuki
 items...
 2nd fire: Akitsuki
 items...
```

**Comment by Javran** [comment]
I'd prefer marking ship that triggers AACI the same way as we mark MVP since we have more room on ship boxes.

for 1st and 2nd triggers we might use different indicators on individual ships.

**Pull request merged**
