### PR TITLE
Accurate landing craft bonus

### PR DESCRIPTION
**Pull request by Javran**
accurate landing craft income bonus, according to formula found on wikia:
2016-05-18_132741_3840x1080_scrot

now T89 & T2 and improvement bonus are all taken into account.

### CODE REVIEW

**Comment by sinsinpub** [comment]
trying it, mine:
image

**Comment by Javran** [comment]
@sinsinpub not seeing any problem, could you give more details?

**Comment by sinsinpub** [comment]
@Javran only the negative ammo is a problem...

**Comment by Javran** [comment]
@sinsinpub Exped38 doesn't give you ammo in the first place. the "-104" part is estimated resupply cost.

**Comment by sinsinpub** [comment]
@Javran oh, I misunderstood it... tooltip why not show up gain part result to match with the SR history page, not only the formula? eg: `480(=400*1.2) - 104`

**Comment by Javran** [comment]
@sinsinpub I'm not sure about expedition history, that's a separated function. maybe the numbers in expedition history come just from KanColle API, which doesn't take re-supply consumption into account.

**Comment by dragonjet** [comment]
seems all good? true the history only shows the actual result, and without resupply calculations, and acts like a predictor of some sort as well. gonna merge this :+1:

**Comment by sinsinpub** [comment]
to clarify the net income value, just change the tooltip a little bit...?
image

**Comment by Javran** [comment]
@sinsinpub I'm good with this change. :+1:

**Pull request merged**
