### PR TITLE
Release 29.0

### PR DESCRIPTION
**Pull request by dragonjet**
#### Updates included in 29.0
* Several languages updated with new Quest translations: [`kc3-translations`](https://github.com/KC3Kai/kc3-translations/commits/master)
* #728 Rank Prediction (PR #1263 by @Javran and @sinsinpub)
  * Show marker on MVPs on result screen
* #1249 Better cross-language subtitle handling (PR #1264 @Javran)
* #1270 Developer tools in Strategy Room by @Javran
  * Foundation and a playground page (PR #1275)
  * Cross-language Translation Previewer (PR #1277)
  * Subtitle testing page (PR #1293)
* #960 Battle Result: Show Contact Plane (PR #1276 by @sinsinpub)
* #1273 Additional credits for subtitle contributors (PR #1273 by @dragonjet)
* #1283 Manual quest control on panel itself (PR #1285 by @sinsinpub)
* #1284 Consider DameCon on Battle predictions (PR #1291 by @Javran)
* Minor fix to `GearManager` (PR #1296 by @Javran)
* #959 AACI battle flag on panel (PR: #1294 by @sinsinpub)
  * Add support for twice triggered AACI stages (PR #1308)
* #1289 Show HP left before Taiha Tooltip when Hover of HP text (PR #1298 by @sinsinpub)
* #1300 Strategy room ship list improvement (PR #1304 by @Javran)
* Backup Loader Update on Strategy Room (PR: #1295 by @Yukinyaa)

### CODE REVIEW

**Comment by Javran** [comment]
what's release date for this version?
hopefully #1284 https://github.com/KC3Kai/kc3-translations/pull/108 can be included if there are one or two more days from now.

**Comment by dragonjet** [comment]
@Javran sure, no problem. haven't put the 29.0 timer on the webstore menu yet, so we can include anything at the moment XD

**Comment by AlphaFinago** [comment]
How to update?

**Comment by dragonjet** [comment]
@AlphaFinago when we're done, we will merge this into the webstore branch

**Comment by dragonjet** [comment]
@KC3Kai/developers @KC3Kai/managers @KC3Kai/translators 

im thinking maybe we can release 29.0 if the active translators are done, just to roll out the TLs into the webstore. additional fixes on features added to 29.0 can be done in succeeding hotfixes this weekend 29.x

**Comment by Javran** [comment]
@dragonjet scn translations are done. just need to update TL pointers.

**Comment by dragonjet** [comment]
alright, I'll double-check JP and TH since they already have TLs but not sure if the IDs are correct

**Comment by Javran** [comment]
@dragonjet also a reminder: Kawakaze k2 needs an icon xD

**Comment by AkagiChan** [comment]
how to Update v29??

**Comment by LostLogia4** [comment]
blob

**Pull request merged**
