### PR TITLE
view level-dependent ship stats

### PR DESCRIPTION
**Pull request by Javran**
Added a slider in ship library, this allows checking level-dependent ship stats at specific levels, namely ASW, LoS and evasion:

2016-07-07_061159_3840x1080_scrot

### CODE REVIEW

**Comment by dragonjet** [comment]
wow nice :+1:

**Comment by sinsinpub** [comment]
suggest using icons instead of 'asw, los, eva'?

**Comment by Javran** [comment]
@sinsinpub that'll be better but I don't have a good idea about how to place them.

**Comment by sinsinpub** [comment]
how about?
image

**Comment by Javran** [comment]
@sinsinpub sorry for late response, good work :+1: could you create a PR for this?

**Pull request merged**
