### PR TITLE
Open fleet manager from sortie/event page

### PR DESCRIPTION
**Pull request by HitomaruKonpaku**
Click on the sortie id now will load the fleet manager
Right click will open in the new tab

### CODE REVIEW

**Comment by HitomaruKonpaku** [comment]
Hmm sorry for the file format I'll recheck it

And should i just remove the right click event?

**Comment by HitomaruKonpaku** [comment]
Is it ok now?

**Comment by Adrymne** [comment]
It does now work from both Maps and Events, which is great. However, ctrl+click is treated as a right-click on OSX, so open-in-new-tab will break. In general, OSX uses cmd instead of ctrl.

**Comment by HitomaruKonpaku** [comment]
@Adrymne so instead of ctrl, alt will be better?

**Comment by Adrymne** [comment]
ctrl is fine - open in new tab is expected behaviour. You just want to listen for the cmd key as well (reference: [Mousetrap](https://github.com/ccampbell/mousetrap/blob/master/mousetrap.js#L135)).

**Pull request merged**
