### PR TITLE
fleet AA and AACI

### PR DESCRIPTION
**Pull request by Javran**
Implements #1684. 

- introduced new module `src/library/modules/AntiAir.js` dedicated to anti-air related calculations
- move mouse over ship icon for proportional shotdown / fixed shotdown / AACI bonus:
2017-01-04_002340_3840x1080_scrot
- fixed shotdown is related to formation (for now I'm using 1.0 as default value):
    - 1.0 for line ahead / echelon / line abreast
    - 1.2 for double line
    - 1.6 for diamond
we might consider showing fixed shotdown for all formations like:

```
Fixed shotdown:
x - y (line ahead / echelon / line abreast)
x - y (double line)
x - y (diamond)
```

which might be a bit on the verbose side.
- I leave all UI design choice to whoever willing to take over. so now i18n is delayed until we can figure out what should be put on the UI. (@Bararun would you mind giving some suggestion about what kind of info will be useful to put on UI?)
- internally `AntiAir.js` is capable of checking whether a particular type of AACI can be performed by a ship (with her equipments taken into account), I think this feature is worth pointing out and might be useful in future.

- documents that might be useful:

    - http://kancolle.wikia.com/wiki/Aerial_Combat
    - http://wikiwiki.jp/kancolle/?%B9%D2%B6%F5%C0%EF#ved2ca21

### CODE REVIEW

**Comment by sinsinpub** [comment]
@ethrundr not ready yet, more UI changes should be applied at least.

**Comment by Javran** [comment]
@sinsinpub thanks for approval and suggestions, here are my responses:

- regarding `categoryEq` thing, I think accepting more than one parameter might be a bit overkill. as most of the time we just need to test on item's category once. having multiple parameters mean we might have to use `indexOf` even if the array contains just one element. plus it's just an internal function - if we want some functional-style helpers around, we can separate that part into another module, we can then think about generalization to make them more powerful.
- for now there are no ships under type `XBB`, so I ignored it.
- combined fleet adjusted anti-air is not supported yet. I want to see whether I have implemented it correctly before dealing with combined fleets.
- I agree with updating tooltip according during battle, I guess that the best we can do; meanwhlie I think user usually keeps an eye on AA stats when they are switching equipments, something like current gun-fit hints might be better, so they can just look at the panel instead of hovering on the icon waiting for tooltips to show up. but they are too many equipments that would affect AA stats (even large caliber main guns), that conflicts with current gun-fit hints.
- extending fleet manager will be good enough I think

**Comment by Javran** [comment]
@sinsinpub Yamato-class are classified as `BB`. I think `XBB` is just like `DDE`, it's been there for a while but is never used. and yes there are no carrier-specific AACIs, but general (non-sub) AACI does work on carriers.

**Comment by sinsinpub** [comment]
Making larger ship library:
image

image

**Comment by sinsinpub** [comment]
@Javran but there is no polymorphism for JS, u mean add more functions with different names to handle Ship  object and Ship Master?

**Comment by Javran** [comment]
> @Javran but there is no polymorphism for JS, u mean add more functions with different names to handle Ship object and Ship Master?

then show me places that you need this polymorphism.

> just accessing the property with || from two classes is okay.

this *is* the check I'm talking about. why is this even necessary?

**Comment by sinsinpub** [comment]
@Javran it's solved. breaking `predicate` into two parts to apparently accept master and Ship Object is the precondition of eliminating polymorphism. I wondering how to code this if it's needed.

**Comment by Javran** [comment]
update: fixed a problem with fleet AA calculation.

@sinsinpub about `sortedPossibleAaciList`, I think simply comparing on `fixed` then tie break by comparing `modifier` (and finally `icon`) will do. we simply don't have enough knowledge to predict things about AACI.

also just FYI: I had some discussion on ngacn about AACI mechanism, which might have some useful info. but still I don't think that's sufficient for us to see the whole picture. so I just put down the link here:
http://bbs.ngacn.cc/read.php?tid=10692277 (Chinese)

**Comment by Agc0de6** [comment]
Wait, AA calculation?
Can we use this part for #1683?
That would be a great help!
"Пожааааааалуйста!"

**Comment by Javran** [comment]
@Agc0de6 not quite... AA is short for anti-air, but I think what you mean is for figuring out aircraft configurations..

**Comment by Agc0de6** [comment]
@Javran ясно. Sorry for disturbing.

**Comment by Javran** [comment]
looking good. @sinsinpub do you plan on adding more commits to this PR? we could list possible fixed shotdown ranges for different formations but I think for this particular PR we are pretty much done.

**Comment by sinsinpub** [comment]
yes, at least I plan to add the fleet adjusted AA value to panel/Fleet Manager like air power thing. And might list up values affected by formation/AACI triggered.

After reading those wiki texts repeatedly, I notice my misunderstanding. We can only get the Formation and triggered AACI type from battle API, and there is no way for now to get these thing:
 * each individual plane slot size of abyssal ship. I max slot size database could be crafted like our replayer done, but the real slot size at stage2 (after loss of stage1 and phases before) will be hard to be guessed.
 * there is no way to know which shijpgirl is selected to do the AA fire towards enemy plane slot.
So calculation of real shot down will not be gotten real-time during battle activity, it is only able to be done as an 'AA fire simulator' at SRoom by manually inputting the enemy slot size, chosen formation, triggered AACI, so on. This should be done later in another PR.

btw, the slot size DB of abyssal ships should be the precondition for building the air power calculator related to #1683.

**Comment by Javran** [comment]
are we done for this particular PR? I'd prefer to make things available in master branch asap, new features can always be added later and have another dedicated PR for it. (and it will be more convenient: for now I can't give approval to these followup commits because technically I'm the owner of this PR)

**Comment by sinsinpub** [comment]
np, just let me open another PR (don't remove branch yet, still on this branch)

**Comment by Javran** [comment]
as a side note, perhaps next time we could try opening PRs to `dev-xxx` branches and see how it goes.

**Comment by Javran** [comment]
merging this as we've all agreed, branch `dev-anti-air` should be kept for further development.

**Comment by Bararun** [comment]
This tool should at least be as good as EO's one, I'm amazed you still hadn't talked about some of the features included on it.

https://github.com/silfumus/ElectronicObserver

https://github.com/andanteyk/ElectronicObserver

**Comment by Javran** [comment]
@Bararun I don't think simply giving us 2 repo links is saying anything...

**Comment by Bararun** [comment]
I figured that actually seeing for yourself the set of features that include the EO's "AA Defense Detail" tool would be more useful than me simply telling you about then.

**Pull request merged**
