### PR TITLE
Release 30.9.2

### LINKED ISSUE #1529: Little display problem in Ship List for Chiyoda Kou Kai
Hello

I noticed that in the Ship List page of the Strategy Room, the name of Chiyoda Kou Kai is not displayed correctly: "Kai" is missing.

chiyoda kou kai
_(the excerpt of the side panel is here to show that it is really Chiyoda Kou Kai in fact)_

I didn't see that problem elsewhere or for another ship.

### PR DESCRIPTION
**Pull request by dragonjet**
# Release 30.9.2

----
## Features and Enhancements
* Add customized font family for TCN (`fbac2d4` by @sinsinpub )
  * `Helvetica Neue", Helvetica, "Microsoft JhengHei", "Microsoft JhengHei UI", Arial,"Heiti TC", sans-serif`
* Updating maintenance time in the menu (`e375469` by @Javran)
* Support automatic resetting of quarterly quests (`6816fa7` by @sinsinpub )
* Update TP multi values (`b2de07a` by @sinsinpub )
* #1523 New icons for sazanami, uranami (`72a4b0a` by @dragonjet)
* Strategy Room: Master Viewer: Seasonals / SWF Update (`c7e6de3` by @dragonjet)
  * Library > Updates: now show seasonal CGs and now a blank, blue container
  * Library > Updates: separated section of seasonals, new abyssal ships, from new player ships
  * Library > Ships: now show a larger CG viewer for seasonals
* Updated Akashi improvement list (`bad9739` by @nonsensed)
  * Warspite's 38.1cm guns

----
## Bug Fixes
* Fix fleet manager equip name span issue (`fbac2d4` by @sinsinpub )
* Close #1529 Shiplist multi-line names not shown in full (`8d389ed` by @sinsinpub)

----
## Translations and Language Files
[_See full list of commits in the translation repository_](https://github.com/KC3Kai/kc3-translations/commits/master)

* TCN
  * Added translations on OSAPI options by @kololz 
  * Added translations about unTL options by @angel84326
    * Main panel, LBAS panel, Setting page and About page
* EN 
  * Subtitle refinements: Amatsukaze, Nagato, Souryuu, Minazuki, Aquila by @nonsensed 
  * Subtitle refinements: Amatsukaze, Souryuu, Hiryuu, Suzuya, misc by @nonsensed 
  * Subtitle refinements: Zuikaku, Z3, Suzuya, Takao, misc by @nonsensed 
  * Add unlocks for period quests by @sinsinpub 
  * New quests, mark quarterlies by @nonsensed 
  * Subtitle updates by @nonsensed 
    * half-baked potato, turkey, mutsu declares impending doom, misc
    * make counters (1st vs first) more consistent
    * clean up Hagikaze kai/nonkai double lines
* TH
  * Updated Sept 7 quests by @arialypse 
  * Subtitles: Mogami, Uranami, Sakawa, Kinu, Hatsukaze by @arialypse 
  * Subtitles: Hiryuu Kai Ni, Souryuu Kai Ni, Mikuma, Minazuki by @arialypse 
  * Subtitles: I-58, I-168, I-401, Maruyu, Agano, Yahagi by @arialypse 
  * Added ships: Asagiri. Yugiri. Amagiri. Sagiri by @arialypse 
  * New Quests 17/09/2016 by @arialypse 
* ID
  * Subtitle fixes by @HR-xero 
  * Subtitles: Warspite, Prinz Eugen by @freezebear 
  * Subtitles: Abukuma, Akatsuki, Akebono, Akigumo by @freezebear 
* SCN
  * Subtitle updates (also, dupe removed) by @Javran 
  * Added new quests by @Javran 
  * update remodelGroups by @Javran 
* KR
  * Added Uranami Lines and Updated new quests by @rephira
  * Updated descriptions for new quests by @rephira
* JP
  * Add new quests for Sept 16 by @sinsinpub 
  * Add quotes for Uranami (WIP), fix Shikinami by @sinsinpub

### CODE REVIEW

**Comment by Javran** [comment]
hm @dragonjet could you make icons for Sazanami (#1523) and Uranami? I think that can be done very quick.

**Comment by dragonjet** [comment]
ah yes, I'll make them now

**Comment by nonsensed** [comment]
Hmm... what do you think about getting this one out soon for TL sake? @dragonjet 

Although if there's something coming up and it's better to wait, no problem for me.

**Comment by dragonjet** [comment]
there's no changes that's being waited at the moment, I just have to write the description so we can release :sweat_smile:

**Pull request merged**
