### PR TITLE
Request!

### PR DESCRIPTION
**Pull request by Agc0de6**
@dragonjet What do you think about giving translators rights to translate web.html and api.html?
I think that english explanation how 2 turn on KC3 and then choosing a player's home language is a little bad.

### CODE REVIEW

**Comment by ethrundr** [comment]
@dragonjet

**Comment by ReiFan49** [comment]
umm i remember @Yukinyaa have said about this actually,
still haven't implement this, sorry

**Comment by dragonjet** [comment]
ah yes, the end goal is to make everything translatable :book: 
we might need an issue entry for this just so it wouldn't be forgotten

**Comment by Agc0de6** [comment]
@dragonjet No prob!

**Pull request merged**
